cmake_minimum_required(VERSION 3.24)

file(MAKE_DIRECTORY "${WORK_ROOT}")
file(TO_CMAKE_PATH "${SOURCE_ROOT}" _source)
file(TO_CMAKE_PATH "${WORK_ROOT}/missing-system-root" _missing)
if(EXISTS "${_missing}")
    message(FATAL_ERROR "The unavailable-root fixture must not exist: ${_missing}")
endif()

foreach(_mode IN ITEMS default empty unavailable)
    set(_root_field "")
    if(_mode STREQUAL "empty")
        set(_root_field ",\"systemRoot\":\"\"")
    elseif(_mode STREQUAL "unavailable")
        set(_root_field ",\"systemRoot\":\"${_missing}\"")
    endif()
    set(_request "${WORK_ROOT}/${_mode}-request.json")
    set(_response "${WORK_ROOT}/${_mode}-response.json")
    file(WRITE "${_request}" "{\"projectRoot\":\"${_source}\",\"locales\":[]${_root_field}}")
    execute_process(
        COMMAND "${BRIDGE}" font-coverage "${_request}" "${_response}"
        RESULT_VARIABLE _result)
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "Tooling bridge invocation failed: ${_result}")
    endif()
    file(READ "${_response}" _json)
    string(JSON _ok GET "${_json}" ok)
    if(_mode STREQUAL "unavailable")
        if(_ok)
            message(FATAL_ERROR "Explicit unavailable system root was ignored: ${_json}")
        endif()
        string(JSON _error GET "${_json}" error)
        string(FIND "${_error}" "system:/fonts/LiberationSans.ttf" _font_position)
        string(FIND "${_error}" "${_missing}" _root_position)
        if(_font_position LESS 0 OR _root_position LESS 0)
            message(FATAL_ERROR "Missing-root diagnostic lacks font/root attribution: ${_json}")
        endif()
    else()
        string(JSON _success GET "${_json}" success)
        if(NOT _ok OR NOT _success)
            message(FATAL_ERROR "Development bridge did not resolve its configured system font: ${_json}")
        endif()
    endif()
endforeach()
