if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()

file(READ "${SOURCE_DIR}/CMakePresets.json" presets_json)

function(find_configure_preset out_index preset_name)
    string(JSON preset_count LENGTH "${presets_json}" configurePresets)
    math(EXPR last_preset "${preset_count} - 1")
    foreach(index RANGE 0 ${last_preset})
        string(JSON name GET "${presets_json}" configurePresets ${index} name)
        if(name STREQUAL preset_name)
            set(${out_index} ${index} PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${out_index} -1 PARENT_SCOPE)
endfunction()

function(require_cache_value preset_name key expected)
    find_configure_preset(index "${preset_name}")
    if(index EQUAL -1)
        message(FATAL_ERROR "Required configure preset not found: ${preset_name}")
    endif()
    string(JSON value ERROR_VARIABLE error GET "${presets_json}" configurePresets ${index} cacheVariables "${key}")
    if(NOT error STREQUAL "NOTFOUND")
        message(FATAL_ERROR "Preset ${preset_name} does not declare ${key}")
    endif()
    if(NOT value STREQUAL expected)
        message(FATAL_ERROR "Preset ${preset_name} must set ${key}=${expected}, got ${value}")
    endif()
endfunction()

foreach(preset IN ITEMS web-debug web-release)
    require_cache_value("${preset}" NOVELTEA_ENABLE_THREADS ON)
    require_cache_value("${preset}" NOVELTEA_JOB_WORKER_COUNT 1)
endforeach()
foreach(preset IN ITEMS web-debug-no-threads web-release-no-threads)
    require_cache_value("${preset}" NOVELTEA_ENABLE_THREADS OFF)
    require_cache_value("${preset}" NOVELTEA_JOB_WORKER_COUNT 0)
endforeach()

message(STATUS "Web threading preset policy verified")
