#include "noveltea/renderer.hpp"

#include "bgfx_renderer_internal.hpp"

#include <SDL3/SDL.h>

#include <bgfx/bgfx.h>
#include <bgfx/platform.h>

#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstring>

// Embedded compiled shader binaries (generated by shaderc --bin2c).
#include "shaders/vs_triangle_glsl.h"
#include "shaders/fs_triangle_glsl.h"
#include "shaders/vs_triangle_essl.h"
#include "shaders/fs_triangle_essl.h"
#include "shaders/vs_triangle_web.h"
#include "shaders/fs_triangle_web.h"

namespace noveltea {

using namespace bgfx_backend;

// ---------------------------------------------------------------------------
// Vertex / index data for a colored triangle
// ---------------------------------------------------------------------------

struct PosColorVertex
{
    float x, y;
    float r, g, b, a;
};

static PosColorVertex s_triangle_vertices[3] = {
    {  0.0f,  0.5f, 1.0f, 0.0f, 0.0f, 1.0f }, // top - red
    { -0.5f, -0.5f, 0.0f, 1.0f, 0.0f, 1.0f }, // bottom-left - green
    {  0.5f, -0.5f, 0.0f, 0.0f, 1.0f, 1.0f }, // bottom-right - blue
};

static const uint16_t s_triangle_indices[3] = { 0, 1, 2 };

static void make_ortho(float* out, float width, float height)
{
    std::memset(out, 0, sizeof(float) * 16);
    out[0] = 2.0f / width;
    out[5] = -2.0f / height;
    out[10] = 1.0f;
    out[12] = -1.0f;
    out[13] = 1.0f;
    out[15] = 1.0f;
}

// ---------------------------------------------------------------------------
// Renderer implementation
// ---------------------------------------------------------------------------

Renderer::Renderer() = default;
Renderer::~Renderer() { shutdown(); }

bool Renderer::initialize(const RendererConfig& config)
{
    if (m_initialized) return true;

    if (!config.native_window) {
        std::fprintf(stderr, "[renderer] no native window provided\n");
        return false;
    }

    bgfx::PlatformData pd{};
    pd.ndt = config.native_display;
    pd.nwh = config.native_window;

    bgfx::Init init;
#if defined(NOVELTEA_PLATFORM_DESKTOP)
    init.type = bgfx::RendererType::OpenGL;
#else
    init.type = bgfx::RendererType::Count; // auto-detect (Android: GLES, Web: GLES/WebGL)
#endif
    init.platformData = pd;
    init.resolution.width = static_cast<uint32_t>(config.width);
    init.resolution.height = static_cast<uint32_t>(config.height);
    init.resolution.reset = config.vsync ? BGFX_RESET_VSYNC : 0;

    if (!bgfx::init(init)) {
        std::fprintf(stderr, "[renderer] bgfx::init failed\n");
        return false;
    }

    m_width = config.width;
    m_height = config.height;
    m_vsync = config.vsync;
    m_initialized = true;

    bgfx::setDebug(BGFX_DEBUG_TEXT);
    bgfx::setViewClear(0, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH, 0x4040c0ff, 1.0f, 0);
    bgfx::setViewRect(ViewGame2D, 0, 0,
        static_cast<uint16_t>(m_width),
        static_cast<uint16_t>(m_height));

    create_triangle();
    create_2d();

    SDL_Log("[renderer] bgfx initialized: %s", renderer_name());
    return true;
}

void Renderer::begin_frame()
{
    bgfx::setViewClear(ViewGame2D, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH, 0x20242cff, 1.0f, 0);
    bgfx::setViewRect(ViewGame2D, 0, 0,
        static_cast<uint16_t>(m_width),
        static_cast<uint16_t>(m_height));
    bgfx::setViewRect(ViewRuntimeUI, 0, 0, static_cast<uint16_t>(m_width), static_cast<uint16_t>(m_height));
    bgfx::setViewRect(ViewTextLab, 0, 0, static_cast<uint16_t>(m_width), static_cast<uint16_t>(m_height));
    bgfx::setViewRect(ViewDebugUI, 0, 0, static_cast<uint16_t>(m_width), static_cast<uint16_t>(m_height));

    float ortho[16];
    make_ortho(ortho, static_cast<float>(m_width), static_cast<float>(m_height));
    bgfx::setViewTransform(ViewGame2D, nullptr, ortho);
    bgfx::setDebug(BGFX_DEBUG_TEXT);
    bgfx::dbgTextClear();
    bgfx::touch(ViewGame2D);

    // Submit triangle geometry for view 0.
    if (bgfx::isValid(bgfx::VertexBufferHandle{m_triangle_vb})
        && bgfx::isValid(bgfx::IndexBufferHandle{m_triangle_ib})
        && bgfx::isValid(bgfx::ProgramHandle{m_triangle_program}))
    {
        bgfx::setVertexBuffer(0, bgfx::VertexBufferHandle{m_triangle_vb});
        bgfx::setIndexBuffer(bgfx::IndexBufferHandle{m_triangle_ib});
        bgfx::submit(ViewGame2D, bgfx::ProgramHandle{m_triangle_program});
    }
}

void Renderer::end_frame()
{
    bgfx::frame();
}

void Renderer::resize(int width, int height)
{
    if (!m_initialized) return;

    m_width = width;
    m_height = height;

    bgfx::reset(
        static_cast<uint32_t>(width),
        static_cast<uint32_t>(height),
        m_vsync ? BGFX_RESET_VSYNC : 0
    );
    bgfx::setViewRect(0, 0, 0,
        static_cast<uint16_t>(width),
        static_cast<uint16_t>(height));
}

void Renderer::shutdown()
{
    if (m_initialized) {
        destroy_2d();
        destroy_triangle();
        bgfx::shutdown();
        m_initialized = false;
        std::printf("[renderer] bgfx shutdown\n");
    }
}

const char* Renderer::renderer_name() const
{
    if (!m_initialized) return "uninitialized";
    return bgfx::getRendererName(bgfx::getRendererType());
}

void Renderer::debug_printf(uint16_t x, uint16_t y, uint8_t color, const char* fmt, ...)
{
    if (!m_initialized) return;
    char buf[256];
    va_list args;
    va_start(args, fmt);
    std::vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    bgfx::dbgTextPrintf(x, y, color, "%s", buf);
}

// ---------------------------------------------------------------------------
// Triangle resource lifecycle
// ---------------------------------------------------------------------------

void Renderer::create_triangle()
{
    const bgfx::RendererType::Enum type = bgfx::getRendererType();

    // Load vertex & fragment shaders.
    bgfx::ShaderHandle vs = load_embedded_shader(
        type,
        vs_triangle_glsl, sizeof(vs_triangle_glsl),
        vs_triangle_essl, sizeof(vs_triangle_essl),
        vs_triangle_web,  sizeof(vs_triangle_web));
    bgfx::ShaderHandle fs = load_embedded_shader(
        type,
        fs_triangle_glsl, sizeof(fs_triangle_glsl),
        fs_triangle_essl, sizeof(fs_triangle_essl),
        fs_triangle_web,  sizeof(fs_triangle_web));

    if (!bgfx::isValid(vs) || !bgfx::isValid(fs)) {
        std::fprintf(stderr, "[renderer] triangle shader load failed; skipping triangle\n");
        if (bgfx::isValid(vs)) bgfx::destroy(vs);
        if (bgfx::isValid(fs)) bgfx::destroy(fs);
        return;
    }

    m_triangle_program = bgfx::createProgram(vs, fs, true /* destroy shaders when program is done */).idx;
    if (!bgfx::isValid(bgfx::ProgramHandle{m_triangle_program})) {
        std::fprintf(stderr, "[renderer] failed to create triangle program\n");
        bgfx::destroy(vs);
        bgfx::destroy(fs);
        return;
    }

    // Vertex layout.
    bgfx::VertexLayout layout;
    layout.begin()
        .add(bgfx::Attrib::Position, 2, bgfx::AttribType::Float)
        .add(bgfx::Attrib::Color0, 4, bgfx::AttribType::Float)
        .end();

    m_triangle_vb = bgfx::createVertexBuffer(
        bgfx::makeRef(s_triangle_vertices, sizeof(s_triangle_vertices)),
        layout
    ).idx;

    m_triangle_ib = bgfx::createIndexBuffer(
        bgfx::makeRef(s_triangle_indices, sizeof(s_triangle_indices))
    ).idx;

    SDL_Log("[renderer] triangle resources created");
}

void Renderer::destroy_triangle()
{
    if (bgfx::isValid(bgfx::ProgramHandle{m_triangle_program})) {
        bgfx::destroy(bgfx::ProgramHandle{m_triangle_program});
    }
    if (bgfx::isValid(bgfx::VertexBufferHandle{m_triangle_vb})) {
        bgfx::destroy(bgfx::VertexBufferHandle{m_triangle_vb});
    }
    if (bgfx::isValid(bgfx::IndexBufferHandle{m_triangle_ib})) {
        bgfx::destroy(bgfx::IndexBufferHandle{m_triangle_ib});
    }

    m_triangle_vb = UINT16_MAX;
    m_triangle_ib = UINT16_MAX;
    m_triangle_program = UINT16_MAX;

    SDL_Log("[renderer] triangle resources destroyed");
}

} // namespace noveltea
