set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Darwin)

set(VCPKG_C_FLAGS " ")
set(VCPKG_CXX_FLAGS "-fno-exceptions -fno-rtti -DITLIB_FLAT_MAP_NO_THROW -DJSON_NOEXCEPTION=1 -DSOL_NO_EXCEPTIONS=1 -DSOL_NO_RTTI=1 -DRMLUI_CUSTOM_RTTI")
