set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_C_FLAGS " ")
set(VCPKG_CXX_FLAGS "/GR- /EHs-c- /D_HAS_EXCEPTIONS=0 /DITLIB_FLAT_MAP_NO_THROW /DJSON_NOEXCEPTION=1 /DSOL_NO_EXCEPTIONS=1 /DSOL_NO_RTTI=1 /DRMLUI_CUSTOM_RTTI")
