// AUTO-GENERATED by scripts/generate-material-contract-registry.mjs. DO NOT EDIT.
#pragma once

#include "noveltea/render/material_contract.hpp"

#include <array>
#include <string_view>

// clang-format off
namespace noveltea::generated_material_contracts {

inline constexpr std::string_view fingerprint_algorithm = "sha256";
inline constexpr std::string_view fingerprint_encoding = "canonical-json-v1";

inline constexpr std::array<MaterialContractInterfaceSlot, 3> role_engine_2d_attributes{{
    {.name = "a_position", .physical_type = "vec2", .semantic = "POSITION"},
    {.name = "a_texcoord0", .physical_type = "vec2", .semantic = "TEXCOORD0"},
    {.name = "a_color0", .physical_type = "vec4", .semantic = "COLOR0"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 2> role_engine_2d_varyings{{
    {.name = "v_texcoord0", .physical_type = "vec2", .semantic = "TEXCOORD0"},
    {.name = "v_color0", .physical_type = "vec4", .semantic = "COLOR0"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 1> role_engine_2d_predefined_uniforms{{
    {.name = "u_modelViewProj", .physical_type = "mat4", .semantic = "bgfx.model_view_projection"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 0> role_engine_2d_renderer_uniforms{{
}};

inline constexpr std::array<MaterialContractSamplerSlot, 1> role_engine_2d_samplers{{
    {
        .name = "s_texColor",
        .semantic = "engine.draw_texture",
        .physical_type = "texture2d",
        .stage = 0,
        .source_ownership = "renderer",
        .address_policy = MaterialContractPolicyValues{.values = {"clamp", "repeat", ""}, .count = 2},
        .filter_policy = MaterialContractPolicyValues{.values = {"inherit", "nearest", "linear"}, .count = 3},
        .observation = "rgba-color",
    },
}};

inline constexpr std::array<MaterialContractStandardSemantic, 7> role_engine_2d_standard_semantics{{
    {.semantic = "engine.time", .logical_type = "float"},
    {.semantic = "engine.paint_dimensions", .logical_type = "vec2"},
    {.semantic = "engine.reference_to_world_raster_scale", .logical_type = "vec2"},
    {.semantic = "engine.context_logical_to_raster_scale", .logical_type = "vec2"},
    {.semantic = "engine.viewport_pixel_dimensions", .logical_type = "vec2"},
    {.semantic = "engine.pointer_position", .logical_type = "vec2"},
    {.semantic = "engine.pointer_valid", .logical_type = "bool"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 3> role_active_text_attributes{{
    {.name = "a_position", .physical_type = "vec2", .semantic = "POSITION"},
    {.name = "a_texcoord0", .physical_type = "vec2", .semantic = "TEXCOORD0"},
    {.name = "a_color0", .physical_type = "vec4", .semantic = "COLOR0"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 2> role_active_text_varyings{{
    {.name = "v_texcoord0", .physical_type = "vec2", .semantic = "TEXCOORD0"},
    {.name = "v_color0", .physical_type = "vec4", .semantic = "COLOR0"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 1> role_active_text_predefined_uniforms{{
    {.name = "u_modelViewProj", .physical_type = "mat4", .semantic = "bgfx.model_view_projection"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 0> role_active_text_renderer_uniforms{{
}};

inline constexpr std::array<MaterialContractSamplerSlot, 1> role_active_text_samplers{{
    {
        .name = "s_textAtlas",
        .semantic = "engine.glyph_atlas",
        .physical_type = "texture2d",
        .stage = 0,
        .source_ownership = "renderer",
        .address_policy = MaterialContractPolicyValues{.values = {"clamp", "", ""}, .count = 1},
        .filter_policy = MaterialContractPolicyValues{.values = {"linear", "", ""}, .count = 1},
        .observation = "alpha-coverage",
    },
}};

inline constexpr std::array<MaterialContractStandardSemantic, 7> role_active_text_standard_semantics{{
    {.semantic = "engine.time", .logical_type = "float"},
    {.semantic = "engine.paint_dimensions", .logical_type = "vec2"},
    {.semantic = "engine.reference_to_world_raster_scale", .logical_type = "vec2"},
    {.semantic = "engine.context_logical_to_raster_scale", .logical_type = "vec2"},
    {.semantic = "engine.viewport_pixel_dimensions", .logical_type = "vec2"},
    {.semantic = "engine.pointer_position", .logical_type = "vec2"},
    {.semantic = "engine.pointer_valid", .logical_type = "bool"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 3> role_rmlui_decorator_attributes{{
    {.name = "a_position", .physical_type = "vec2", .semantic = "POSITION"},
    {.name = "a_texcoord0", .physical_type = "vec2", .semantic = "TEXCOORD0"},
    {.name = "a_color0", .physical_type = "vec4", .semantic = "COLOR0"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 2> role_rmlui_decorator_varyings{{
    {.name = "v_texcoord0", .physical_type = "vec2", .semantic = "TEXCOORD0"},
    {.name = "v_color0", .physical_type = "vec4", .semantic = "COLOR0"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 0> role_rmlui_decorator_predefined_uniforms{{
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 3> role_rmlui_decorator_renderer_uniforms{{
    {.name = "u_projection", .physical_type = "mat4", .semantic = "rmlui.projection"},
    {.name = "u_transform", .physical_type = "mat4", .semantic = "rmlui.transform"},
    {.name = "u_translate", .physical_type = "vec4", .semantic = "rmlui.translation"},
}};

inline constexpr std::array<MaterialContractSamplerSlot, 1> role_rmlui_decorator_samplers{{
    {
        .name = "s_texColor",
        .semantic = "rmlui.decorator_texture",
        .physical_type = "texture2d",
        .stage = 0,
        .source_ownership = "renderer",
        .address_policy = MaterialContractPolicyValues{.values = {"clamp", "", ""}, .count = 1},
        .filter_policy = MaterialContractPolicyValues{.values = {"linear", "", ""}, .count = 1},
        .observation = "rgba-color",
    },
}};

inline constexpr std::array<MaterialContractStandardSemantic, 7> role_rmlui_decorator_standard_semantics{{
    {.semantic = "engine.time", .logical_type = "float"},
    {.semantic = "engine.paint_dimensions", .logical_type = "vec2"},
    {.semantic = "engine.context_logical_to_raster_scale", .logical_type = "vec2"},
    {.semantic = "engine.viewport_pixel_dimensions", .logical_type = "vec2"},
    {.semantic = "engine.pointer_position", .logical_type = "vec2"},
    {.semantic = "engine.pointer_valid", .logical_type = "bool"},
    {.semantic = "rmlui.media_query_resolution", .logical_type = "float"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 2> role_postprocess_attributes{{
    {.name = "a_position", .physical_type = "vec2", .semantic = "POSITION"},
    {.name = "a_texcoord0", .physical_type = "vec2", .semantic = "TEXCOORD0"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 1> role_postprocess_varyings{{
    {.name = "v_texcoord0", .physical_type = "vec2", .semantic = "TEXCOORD0"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 1> role_postprocess_predefined_uniforms{{
    {.name = "u_modelViewProj", .physical_type = "mat4", .semantic = "bgfx.model_view_projection"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 0> role_postprocess_renderer_uniforms{{
}};

inline constexpr std::array<MaterialContractSamplerSlot, 1> role_postprocess_samplers{{
    {
        .name = "s_texColor",
        .semantic = "engine.postprocess_source",
        .physical_type = "texture2d",
        .stage = 0,
        .source_ownership = "renderer",
        .address_policy = MaterialContractPolicyValues{.values = {"clamp", "", ""}, .count = 1},
        .filter_policy = MaterialContractPolicyValues{.values = {"linear", "", ""}, .count = 1},
        .observation = "premultiplied-rgba",
    },
}};

inline constexpr std::array<MaterialContractStandardSemantic, 5> role_postprocess_standard_semantics{{
    {.semantic = "engine.time", .logical_type = "float"},
    {.semantic = "engine.paint_dimensions", .logical_type = "vec2"},
    {.semantic = "engine.viewport_pixel_dimensions", .logical_type = "vec2"},
    {.semantic = "engine.pointer_position", .logical_type = "vec2"},
    {.semantic = "engine.pointer_valid", .logical_type = "bool"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 3> role_hotspot_overlay_attributes{{
    {.name = "a_position", .physical_type = "vec2", .semantic = "POSITION"},
    {.name = "a_texcoord0", .physical_type = "vec2", .semantic = "TEXCOORD0"},
    {.name = "a_color0", .physical_type = "vec4", .semantic = "COLOR0"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 2> role_hotspot_overlay_varyings{{
    {.name = "v_texcoord0", .physical_type = "vec2", .semantic = "TEXCOORD0"},
    {.name = "v_color0", .physical_type = "vec4", .semantic = "COLOR0"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 1> role_hotspot_overlay_predefined_uniforms{{
    {.name = "u_modelViewProj", .physical_type = "mat4", .semantic = "bgfx.model_view_projection"},
}};

inline constexpr std::array<MaterialContractInterfaceSlot, 0> role_hotspot_overlay_renderer_uniforms{{
}};

inline constexpr std::array<MaterialContractSamplerSlot, 2> role_hotspot_overlay_samplers{{
    {
        .name = "s_hotspotImage",
        .semantic = "engine.hotspot_image",
        .physical_type = "texture2d",
        .stage = 0,
        .source_ownership = "renderer",
        .address_policy = MaterialContractPolicyValues{.values = {"clamp", "", ""}, .count = 1},
        .filter_policy = MaterialContractPolicyValues{.values = {"inherit", "", ""}, .count = 1},
        .observation = "rgba-image-alpha-coverage",
    },
    {
        .name = "s_hotspotMask",
        .semantic = "engine.hotspot_mask",
        .physical_type = "texture2d",
        .stage = 1,
        .source_ownership = "renderer",
        .address_policy = MaterialContractPolicyValues{.values = {"clamp", "", ""}, .count = 1},
        .filter_policy = MaterialContractPolicyValues{.values = {"nearest", "", ""}, .count = 1},
        .observation = "red-normalized-coverage",
    },
}};

inline constexpr std::array<MaterialContractStandardSemantic, 12> role_hotspot_overlay_standard_semantics{{
    {.semantic = "engine.time", .logical_type = "float"},
    {.semantic = "engine.paint_dimensions", .logical_type = "vec2"},
    {.semantic = "engine.reference_to_world_raster_scale", .logical_type = "vec2"},
    {.semantic = "engine.context_logical_to_raster_scale", .logical_type = "vec2"},
    {.semantic = "engine.viewport_pixel_dimensions", .logical_type = "vec2"},
    {.semantic = "engine.pointer_position", .logical_type = "vec2"},
    {.semantic = "engine.pointer_valid", .logical_type = "bool"},
    {.semantic = "engine.hotspot_bounds", .logical_type = "vec4"},
    {.semantic = "engine.hotspot_hovered", .logical_type = "bool"},
    {.semantic = "engine.hotspot_pressed", .logical_type = "bool"},
    {.semantic = "engine.hotspot_image_dimensions", .logical_type = "vec2"},
    {.semantic = "engine.hotspot_mask_dimensions", .logical_type = "vec2"},
}};

inline constexpr std::array<MaterialRoleContract, 5> roles{{
    {
        .id = "engine-2d",
        .attributes = role_engine_2d_attributes,
        .varyings = role_engine_2d_varyings,
        .predefined_uniforms = role_engine_2d_predefined_uniforms,
        .renderer_uniforms = role_engine_2d_renderer_uniforms,
        .samplers = role_engine_2d_samplers,
        .standard_semantics = role_engine_2d_standard_semantics,
        .pipeline_state = {
            .blend = "premultiplied-alpha",
            .output_alpha = "premultiplied",
        },
    },
    {
        .id = "active-text",
        .attributes = role_active_text_attributes,
        .varyings = role_active_text_varyings,
        .predefined_uniforms = role_active_text_predefined_uniforms,
        .renderer_uniforms = role_active_text_renderer_uniforms,
        .samplers = role_active_text_samplers,
        .standard_semantics = role_active_text_standard_semantics,
        .pipeline_state = {
            .blend = "premultiplied-alpha",
            .output_alpha = "premultiplied",
        },
    },
    {
        .id = "rmlui-decorator",
        .attributes = role_rmlui_decorator_attributes,
        .varyings = role_rmlui_decorator_varyings,
        .predefined_uniforms = role_rmlui_decorator_predefined_uniforms,
        .renderer_uniforms = role_rmlui_decorator_renderer_uniforms,
        .samplers = role_rmlui_decorator_samplers,
        .standard_semantics = role_rmlui_decorator_standard_semantics,
        .pipeline_state = {
            .blend = "premultiplied-alpha",
            .output_alpha = "premultiplied",
        },
    },
    {
        .id = "postprocess",
        .attributes = role_postprocess_attributes,
        .varyings = role_postprocess_varyings,
        .predefined_uniforms = role_postprocess_predefined_uniforms,
        .renderer_uniforms = role_postprocess_renderer_uniforms,
        .samplers = role_postprocess_samplers,
        .standard_semantics = role_postprocess_standard_semantics,
        .pipeline_state = {
            .blend = "replace",
            .output_alpha = "premultiplied",
        },
    },
    {
        .id = "hotspot-overlay",
        .attributes = role_hotspot_overlay_attributes,
        .varyings = role_hotspot_overlay_varyings,
        .predefined_uniforms = role_hotspot_overlay_predefined_uniforms,
        .renderer_uniforms = role_hotspot_overlay_renderer_uniforms,
        .samplers = role_hotspot_overlay_samplers,
        .standard_semantics = role_hotspot_overlay_standard_semantics,
        .pipeline_state = {
            .blend = "premultiplied-alpha",
            .output_alpha = "premultiplied",
        },
    },
}};

inline constexpr std::array<MaterialContractCapability, 1> preset_engine_2d_sampler_capabilities{{
    {.slot = "s_texColor", .state = "required"},
}};

inline constexpr std::array<MaterialContractCapability, 1> preset_active_text_sampler_capabilities{{
    {.slot = "s_textAtlas", .state = "required"},
}};

inline constexpr std::array<MaterialContractCapability, 1> preset_rmlui_decorator_sampler_capabilities{{
    {.slot = "s_texColor", .state = "required"},
}};

inline constexpr std::array<MaterialContractCapability, 1> preset_postprocess_tint_sampler_capabilities{{
    {.slot = "s_texColor", .state = "required"},
}};

inline constexpr std::array<MaterialContractCapability, 2> preset_hotspot_overlay_alpha_sampler_capabilities{{
    {.slot = "s_hotspotImage", .state = "required"},
    {.slot = "s_hotspotMask", .state = "disabled"},
}};

inline constexpr std::array<MaterialContractCapability, 2> preset_hotspot_overlay_custom_sampler_capabilities{{
    {.slot = "s_hotspotImage", .state = "required"},
    {.slot = "s_hotspotMask", .state = "required"},
}};

inline constexpr std::array<MaterialPresetContract, 6> presets{{
    {
        .id = "engine-2d",
        .label = "Engine 2D",
        .role = "engine-2d",
        .contract_identity = "noveltea.material-preset:engine-2d:1",
        .contract_fingerprint = "sha256:0e4e262891e0e3895803481b735e0747bb62bc49599e4b8de76586139b2e292a",
        .vertex_source = "engine:/vs_quad.sc",
        .fragment_source = "engine:/fs_quad.sc",
        .varying_definition = "engine:/varying.def.sc",
        .program_name = "quad",
        .sampler_capabilities = preset_engine_2d_sampler_capabilities,
        .default_parameters_json = "{}",
        .preview = {
            .fixture = "engine-2d-sprite-checker",
            .geometry = "quad",
            .background = "checker",
        },
        .compatibility_projection_json = "{\"blend\":\"premultiplied-alpha\",\"postprocessScope\":\"world\",\"samplers\":{\"s_texColor\":{}},\"uniforms\":{\"u_useTexture\":{\"default\":1,\"label\":\"Use Texture\",\"type\":\"float\"}}}",
    },
    {
        .id = "active-text",
        .label = "ActiveText",
        .role = "active-text",
        .contract_identity = "noveltea.material-preset:active-text:1",
        .contract_fingerprint = "sha256:c62ec9672871d25d0736f7b093016d8835ea372693b9dab9016ea56d145427e2",
        .vertex_source = "engine:/vs_text.sc",
        .fragment_source = "engine:/fs_text.sc",
        .varying_definition = "engine:/varying.def.sc",
        .program_name = "text",
        .sampler_capabilities = preset_active_text_sampler_capabilities,
        .default_parameters_json = "{}",
        .preview = {
            .fixture = "active-text-glyph-atlas",
            .geometry = "glyphs",
            .background = "dark",
        },
        .compatibility_projection_json = "{\"blend\":\"premultiplied-alpha\",\"postprocessScope\":\"world\",\"samplers\":{\"s_textAtlas\":{}},\"uniforms\":{}}",
    },
    {
        .id = "rmlui-decorator",
        .label = "RmlUi Decorator",
        .role = "rmlui-decorator",
        .contract_identity = "noveltea.material-preset:rmlui-decorator:1",
        .contract_fingerprint = "sha256:4d6fa3ddc7c34a2d7ca9fa8102e0881305a1ea684693b47eff6ebebdddaf4a27",
        .vertex_source = "engine:/vs_rmlui.sc",
        .fragment_source = "engine:/fs_rmlui.sc",
        .varying_definition = "engine:/varying.def.sc",
        .program_name = "rmlui",
        .sampler_capabilities = preset_rmlui_decorator_sampler_capabilities,
        .default_parameters_json = "{}",
        .preview = {
            .fixture = "rmlui-decorator-texture",
            .geometry = "rounded-rect",
            .background = "checker",
        },
        .compatibility_projection_json = "{\"blend\":\"premultiplied-alpha\",\"postprocessScope\":\"world\",\"samplers\":{\"s_texColor\":{}},\"uniforms\":{}}",
    },
    {
        .id = "postprocess-tint",
        .label = "Postprocess Tint",
        .role = "postprocess",
        .contract_identity = "noveltea.material-preset:postprocess-tint:1",
        .contract_fingerprint = "sha256:07983cdd0065e8e8acf3aaf53c6e2c0bb443f8c557561403b0dd4917f4040b10",
        .vertex_source = "engine:/vs_postprocess_tint.sc",
        .fragment_source = "engine:/fs_postprocess_tint.sc",
        .varying_definition = "engine:/varying.def.sc",
        .program_name = "postprocess_tint",
        .sampler_capabilities = preset_postprocess_tint_sampler_capabilities,
        .default_parameters_json = "{\"u_tint\":{\"default\":[1,1,1,1],\"label\":\"Tint\",\"type\":\"color\"}}",
        .preview = {
            .fixture = "postprocess-composed-scene",
            .geometry = "quad",
            .background = "checker",
        },
        .compatibility_projection_json = "{\"blend\":\"premultiplied-alpha\",\"postprocessScope\":\"world\",\"samplers\":{\"s_texColor\":{}},\"uniforms\":{\"u_tint\":{\"default\":[1,1,1,1],\"label\":\"Tint\",\"type\":\"color\"}}}",
    },
    {
        .id = "hotspot-overlay-alpha",
        .label = "Hotspot Overlay (Alpha)",
        .role = "hotspot-overlay",
        .contract_identity = "noveltea.material-preset:hotspot-overlay-alpha:1",
        .contract_fingerprint = "sha256:c6676b68043dcc07e21ad86c5552a11e55784bb294a2aecb2ce0bc531fef378e",
        .vertex_source = "engine:/vs_quad.sc",
        .fragment_source = "engine:/fs_hotspot_alpha.sc",
        .varying_definition = "engine:/varying.def.sc",
        .program_name = "hotspot_alpha",
        .sampler_capabilities = preset_hotspot_overlay_alpha_sampler_capabilities,
        .default_parameters_json = "{}",
        .preview = {
            .fixture = "hotspot-image",
            .geometry = "sprite",
            .background = "checker",
        },
        .compatibility_projection_json = "{\"blend\":\"premultiplied-alpha\",\"postprocessScope\":\"world\",\"samplers\":{\"s_hotspotImage\":{\"binding\":\"engine.hotspot_image\"}},\"uniforms\":{\"u_hotspotBounds\":{\"binding\":\"engine.hotspot_bounds\",\"type\":\"vec4\"},\"u_hotspotHovered\":{\"binding\":\"engine.hotspot_hovered\",\"type\":\"bool\"},\"u_hotspotImageDimensions\":{\"binding\":\"engine.hotspot_image_dimensions\",\"type\":\"vec2\"},\"u_hotspotMaskDimensions\":{\"binding\":\"engine.hotspot_mask_dimensions\",\"type\":\"vec2\"},\"u_hotspotPressed\":{\"binding\":\"engine.hotspot_pressed\",\"type\":\"bool\"},\"u_time\":{\"binding\":\"engine.time\",\"label\":\"Time\",\"type\":\"float\"}}}",
    },
    {
        .id = "hotspot-overlay-custom",
        .label = "Hotspot Overlay (Custom Mask)",
        .role = "hotspot-overlay",
        .contract_identity = "noveltea.material-preset:hotspot-overlay-custom:1",
        .contract_fingerprint = "sha256:14cf3e7f960ec5334f2135358daee569b66949dfecb0b1ae0eac5b57c39e9434",
        .vertex_source = "engine:/vs_quad.sc",
        .fragment_source = "engine:/fs_hotspot_custom.sc",
        .varying_definition = "engine:/varying.def.sc",
        .program_name = "hotspot_custom",
        .sampler_capabilities = preset_hotspot_overlay_custom_sampler_capabilities,
        .default_parameters_json = "{}",
        .preview = {
            .fixture = "hotspot-image-mask",
            .geometry = "sprite",
            .background = "checker",
        },
        .compatibility_projection_json = "{\"blend\":\"premultiplied-alpha\",\"postprocessScope\":\"world\",\"samplers\":{\"s_hotspotImage\":{\"binding\":\"engine.hotspot_image\"},\"s_hotspotMask\":{\"binding\":\"engine.hotspot_mask\"}},\"uniforms\":{\"u_hotspotBounds\":{\"binding\":\"engine.hotspot_bounds\",\"type\":\"vec4\"},\"u_hotspotHovered\":{\"binding\":\"engine.hotspot_hovered\",\"type\":\"bool\"},\"u_hotspotImageDimensions\":{\"binding\":\"engine.hotspot_image_dimensions\",\"type\":\"vec2\"},\"u_hotspotMaskDimensions\":{\"binding\":\"engine.hotspot_mask_dimensions\",\"type\":\"vec2\"},\"u_hotspotPressed\":{\"binding\":\"engine.hotspot_pressed\",\"type\":\"bool\"},\"u_time\":{\"binding\":\"engine.time\",\"label\":\"Time\",\"type\":\"float\"}}}",
    },
}};

} // namespace noveltea::generated_material_contracts
// clang-format on
