cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED NOVELTEA_PLAYER OR NOT EXISTS "${NOVELTEA_PLAYER}")
  message(FATAL_ERROR "NOVELTEA_PLAYER must name an existing player executable")
endif()
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  set(audit_platform "linux")
  set(audit_checks "\"linux-dependency-closure\",\"linux-rpath\"")
  set(audit_detail "ELF dependency closure and runtime paths passed.")
  execute_process(COMMAND readelf -d "${NOVELTEA_PLAYER}" OUTPUT_VARIABLE deps COMMAND_ERROR_IS_FATAL ANY)
  if(deps MATCHES "RPATH.*(/home/|/tmp/|build/)" OR deps MATCHES "RUNPATH.*(/home/|/tmp/|build/)")
    message(FATAL_ERROR "Player contains a nonportable ELF runtime path")
  endif()
  execute_process(COMMAND ldd "${NOVELTEA_PLAYER}" OUTPUT_VARIABLE closure COMMAND_ERROR_IS_FATAL ANY)
  if(closure MATCHES "not found")
    message(FATAL_ERROR "Player has unresolved ELF dependencies:\n${closure}")
  endif()
  if(DEFINED NOVELTEA_MAX_GLIBC_VERSION)
    find_program(OBJDUMP objdump REQUIRED)
    execute_process(COMMAND "${OBJDUMP}" -T "${NOVELTEA_PLAYER}" OUTPUT_VARIABLE symbols COMMAND_ERROR_IS_FATAL ANY)
    string(REGEX MATCHALL "GLIBC_[0-9]+\\.[0-9]+" glibc_versions "${symbols}")
    foreach(glibc IN LISTS glibc_versions)
      string(REPLACE "GLIBC_" "" version "${glibc}")
      if(version VERSION_GREATER NOVELTEA_MAX_GLIBC_VERSION)
        message(FATAL_ERROR
          "Player requires ${glibc}, newer than supported baseline GLIBC_${NOVELTEA_MAX_GLIBC_VERSION}")
      endif()
    endforeach()
    set(audit_detail "ELF dependency closure, runtime paths, and GLIBC_${NOVELTEA_MAX_GLIBC_VERSION} baseline passed.")
  endif()
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
  set(audit_platform "macos")
  set(audit_checks "\"macos-install-name-closure\"")
  set(audit_detail "Mach-O install-name dependency closure passed.")
  execute_process(COMMAND otool -L "${NOVELTEA_PLAYER}" OUTPUT_VARIABLE closure COMMAND_ERROR_IS_FATAL ANY)
  string(REPLACE "\n" ";" dependency_lines "${closure}")
  # otool prints the inspected executable path as its first line; only audit
  # subsequent install names so an absolute CI workspace path is not mistaken
  # for a runtime dependency.
  if(dependency_lines)
    list(POP_FRONT dependency_lines)
  endif()
  foreach(dependency_line IN LISTS dependency_lines)
    string(STRIP "${dependency_line}" dependency_line)
    if(dependency_line MATCHES "^(/Users/|/opt/homebrew/|/usr/local/)")
      message(FATAL_ERROR "Player contains a nonportable Mach-O dependency:\n${dependency_line}")
    endif()
  endforeach()
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
  set(audit_platform "windows")
  set(audit_checks "\"windows-dependency-closure\"")
  set(audit_detail "PE dependency closure contains no debug runtime imports.")
  find_program(DUMPBIN dumpbin)
  if(NOT DUMPBIN)
    message(FATAL_ERROR "dumpbin is required for the Windows dependency audit")
  endif()
  execute_process(COMMAND "${DUMPBIN}" /DEPENDENTS "${NOVELTEA_PLAYER}" OUTPUT_VARIABLE closure COMMAND_ERROR_IS_FATAL ANY)
  string(TOLOWER "${closure}" closure_lower)
  if(closure_lower MATCHES "vcruntime[0-9]+d|ucrtbased|msvcp[0-9]+d")
    message(FATAL_ERROR "Release player imports debug runtime DLLs:\n${closure}")
  endif()
endif()

if(DEFINED NOVELTEA_AUDIT_REPORT)
  if(NOT DEFINED audit_platform)
    message(FATAL_ERROR "Dependency audit evidence is unsupported on ${CMAKE_HOST_SYSTEM_NAME}")
  endif()
  get_filename_component(audit_report_directory "${NOVELTEA_AUDIT_REPORT}" DIRECTORY)
  file(MAKE_DIRECTORY "${audit_report_directory}")
  file(WRITE "${NOVELTEA_AUDIT_REPORT}"
    "{\"format\":\"noveltea-player-dependency-audit\",\"platform\":\"${audit_platform}\",\"status\":\"passed\",\"checks\":[${audit_checks}],\"detail\":\"${audit_detail}\"}\n")
endif()
