cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED NOVELTEA_PLAYER OR NOT EXISTS "${NOVELTEA_PLAYER}")
  message(FATAL_ERROR "NOVELTEA_PLAYER must name an existing player executable")
endif()
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  execute_process(COMMAND readelf -d "${NOVELTEA_PLAYER}" OUTPUT_VARIABLE deps COMMAND_ERROR_IS_FATAL ANY)
  if(deps MATCHES "RPATH.*(/home/|/tmp/|build/)" OR deps MATCHES "RUNPATH.*(/home/|/tmp/|build/)")
    message(FATAL_ERROR "Player contains a nonportable ELF runtime path")
  endif()
  execute_process(COMMAND ldd "${NOVELTEA_PLAYER}" OUTPUT_VARIABLE closure COMMAND_ERROR_IS_FATAL ANY)
  if(closure MATCHES "not found")
    message(FATAL_ERROR "Player has unresolved ELF dependencies:\n${closure}")
  endif()
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
  execute_process(COMMAND otool -L "${NOVELTEA_PLAYER}" OUTPUT_VARIABLE closure COMMAND_ERROR_IS_FATAL ANY)
  if(closure MATCHES "(/Users/|/opt/homebrew/|/usr/local/)")
    message(FATAL_ERROR "Player contains a nonportable Mach-O dependency:\n${closure}")
  endif()
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
  find_program(DUMPBIN dumpbin)
  if(NOT DUMPBIN)
    message(FATAL_ERROR "dumpbin is required for the Windows dependency audit")
  endif()
  execute_process(COMMAND "${DUMPBIN}" /DEPENDENTS "${NOVELTEA_PLAYER}" OUTPUT_VARIABLE closure COMMAND_ERROR_IS_FATAL ANY)
  string(TOLOWER "${closure}" closure_lower)
  if(closure_lower MATCHES "vcruntime[0-9]+d|ucrtbased|msvcp[0-9]+d")
    message(FATAL_ERROR "Release player imports debug runtime DLLs:\n${closure}")
  endif()
endif()
