cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED SOURCE_ROOT OR NOT DEFINED ALLOWLIST)
    message(FATAL_ERROR "SOURCE_ROOT and ALLOWLIST are required")
endif()

if(NOT DEFINED CLASSIFICATION)
    set(CLASSIFICATION "${SOURCE_ROOT}/cmake/NovelTeaModuleFileClassification.cmake")
endif()

if(NOT EXISTS "${CLASSIFICATION}")
    message(FATAL_ERROR "Module classification does not exist: ${CLASSIFICATION}")
endif()
if(NOT EXISTS "${ALLOWLIST}")
    message(FATAL_ERROR "Module boundary allowlist does not exist: ${ALLOWLIST}")
endif()

set(module_targets
    noveltea_domain
    noveltea_content
    noveltea_runtime
    noveltea_presentation
    noveltea_script_lua
    noveltea_engine)

include("${CLASSIFICATION}")

if(NOT NOVELTEA_MODULE_CLASSIFICATION_VERSION EQUAL 1)
    message(FATAL_ERROR
        "Unsupported module classification version: ${NOVELTEA_MODULE_CLASSIFICATION_VERSION}")
endif()
if(NOT "${NOVELTEA_MODULE_CLASSIFICATION_TARGETS}" STREQUAL "${module_targets}")
    message(FATAL_ERROR
        "Module boundary policy requires exactly the six approved production targets.\n"
        "Expected: ${module_targets}\n"
        "Actual:   ${NOVELTEA_MODULE_CLASSIFICATION_TARGETS}")
endif()

get_cmake_property(defined_variables VARIABLES)
foreach(variable IN LISTS defined_variables)
    if(variable MATCHES "^NOVELTEA_MODULE_FILES_(.+)$")
        set(classified_target "${CMAKE_MATCH_1}")
        list(FIND module_targets "${classified_target}" classified_target_index)
        if(classified_target_index EQUAL -1)
            message(FATAL_ERROR "Unexpected production module classification target: ${classified_target}")
        endif()
    endif()
endforeach()

file(GLOB_RECURSE production_files
    LIST_DIRECTORIES FALSE
    RELATIVE "${SOURCE_ROOT}"
    "${SOURCE_ROOT}/engine/include/*.h"
    "${SOURCE_ROOT}/engine/include/*.hpp"
    "${SOURCE_ROOT}/engine/include/*.c"
    "${SOURCE_ROOT}/engine/include/*.cc"
    "${SOURCE_ROOT}/engine/include/*.cpp"
    "${SOURCE_ROOT}/engine/include/*.cxx"
    "${SOURCE_ROOT}/engine/src/*.h"
    "${SOURCE_ROOT}/engine/src/*.hpp"
    "${SOURCE_ROOT}/engine/src/*.c"
    "${SOURCE_ROOT}/engine/src/*.cc"
    "${SOURCE_ROOT}/engine/src/*.cpp"
    "${SOURCE_ROOT}/engine/src/*.cxx")
list(SORT production_files)

set(classified_paths "")
set(classified_entries "")
foreach(module IN LISTS module_targets)
    if(NOT DEFINED NOVELTEA_MODULE_FILES_${module})
        message(FATAL_ERROR "Missing production file classification for ${module}")
    endif()
    foreach(path IN LISTS NOVELTEA_MODULE_FILES_${module})
        if(path MATCHES "^/" OR path MATCHES "(^|/)[.][.](/|$)")
            message(FATAL_ERROR "Module classification path must be repository-relative: ${path}")
        endif()
        if(NOT EXISTS "${SOURCE_ROOT}/${path}")
            message(FATAL_ERROR "Module classification contains a stale path: ${path}")
        endif()
        list(FIND production_files "${path}" production_path_index)
        if(production_path_index EQUAL -1)
            message(FATAL_ERROR "Module classification path is outside the production tree: ${path}")
        endif()
        list(FIND classified_paths "${path}" duplicate_path_index)
        if(NOT duplicate_path_index EQUAL -1)
            message(FATAL_ERROR "Module classification contains a duplicate path: ${path}")
        endif()
        list(APPEND classified_paths "${path}")
        list(APPEND classified_entries "${path}|${module}")
    endforeach()
endforeach()

set(unclassified_production_files "${production_files}")
foreach(path IN LISTS classified_paths)
    list(REMOVE_ITEM unclassified_production_files "${path}")
endforeach()
if(unclassified_production_files)
    list(JOIN unclassified_production_files "\n  " unclassified_text)
    message(FATAL_ERROR
        "Production files are missing module classification and cannot be policy-scanned:\n  ${unclassified_text}")
endif()

function(module_owner_for_path path out_var)
    set(result "")
    foreach(entry IN LISTS classified_entries)
        string(REPLACE "|" ";" fields "${entry}")
        list(GET fields 0 entry_path)
        if(entry_path STREQUAL path)
            list(GET fields 1 result)
            break()
        endif()
    endforeach()
    set(${out_var} "${result}" PARENT_SCOPE)
endfunction()

function(module_dependency_allowed source_module dependency_module out_var)
    set(allowed FALSE)
    if(source_module STREQUAL dependency_module)
        set(allowed TRUE)
    elseif(source_module STREQUAL "noveltea_content" AND
           dependency_module STREQUAL "noveltea_domain")
        set(allowed TRUE)
    elseif(source_module STREQUAL "noveltea_runtime" AND
           dependency_module MATCHES "^noveltea_(domain|content)$")
        set(allowed TRUE)
    elseif(source_module STREQUAL "noveltea_presentation" AND
           dependency_module MATCHES "^noveltea_(domain|runtime)$")
        set(allowed TRUE)
    elseif(source_module STREQUAL "noveltea_script_lua" AND
           dependency_module MATCHES "^noveltea_(domain|runtime)$")
        set(allowed TRUE)
    elseif(source_module STREQUAL "noveltea_engine")
        set(allowed TRUE)
    endif()
    set(${out_var} "${allowed}" PARENT_SCOPE)
endfunction()

function(external_include_family include_token out_var)
    set(family "")
    if(include_token MATCHES "^nlohmann/")
        set(family "nlohmann-json")
    elseif(include_token MATCHES "^(miniz/|miniz\.h$)")
        set(family "miniz")
    elseif(include_token MATCHES "^(lua\.hpp|lua\.h|lauxlib\.h|lualib\.h|luaconf\.h|sol/)")
        set(family "lua")
    elseif(include_token MATCHES "^(SDL3/|SDL\.h$)")
        set(family "sdl")
    elseif(include_token MATCHES "^(bgfx/|bimg/|bx/)")
        set(family "bgfx")
    elseif(include_token MATCHES "^RmlUi/")
        set(family "rmlui")
    elseif(include_token MATCHES "^(imgui\.h$|imgui/)")
        set(family "imgui")
    elseif(include_token MATCHES "^(miniaudio\.h$|miniaudio/)")
        set(family "miniaudio")
    elseif(include_token MATCHES "^twink/")
        set(family "twink")
    elseif(include_token MATCHES "^(ft2build\.h$|freetype/|hb[^/]*\.h$|SheenBidi/|linebreak\.h$|unibreak/)")
        set(family "text-backend")
    endif()
    set(${out_var} "${family}" PARENT_SCOPE)
endfunction()

function(external_include_allowed module family out_var)
    set(allowed FALSE)
    if(module STREQUAL "noveltea_engine")
        set(allowed TRUE)
    elseif(module STREQUAL "noveltea_content" AND family MATCHES "^(nlohmann-json|miniz)$")
        set(allowed TRUE)
    elseif(module STREQUAL "noveltea_script_lua" AND family STREQUAL "lua")
        set(allowed TRUE)
    endif()
    set(${out_var} "${allowed}" PARENT_SCOPE)
endfunction()

function(external_target_allowed module dependency out_var)
    set(allowed FALSE)
    if(module STREQUAL "noveltea_engine")
        set(allowed TRUE)
    elseif(module STREQUAL "noveltea_content" AND
           dependency MATCHES "^(nlohmann_json::nlohmann_json|miniz::miniz)$")
        set(allowed TRUE)
    elseif(module STREQUAL "noveltea_script_lua" AND
           dependency MATCHES "^(Lua::Lua|sol2::sol2)$")
        set(allowed TRUE)
    endif()
    set(${out_var} "${allowed}" PARENT_SCOPE)
endfunction()

file(STRINGS "${ALLOWLIST}" allowlist_lines)
set(allowlist_keys "")
foreach(line IN LISTS allowlist_lines)
    string(STRIP "${line}" line)
    if(line STREQUAL "" OR line MATCHES "^#")
        continue()
    endif()

    string(REPLACE "|" ";" fields "${line}")
    list(LENGTH fields field_count)
    if(NOT field_count EQUAL 7)
        message(FATAL_ERROR
            "Malformed module boundary allowlist entry (expected seven fields): ${line}")
    endif()
    list(GET fields 0 kind)
    list(GET fields 1 source)
    list(GET fields 2 dependency)
    list(GET fields 3 owner)
    list(GET fields 4 rationale)
    list(GET fields 5 removal_condition)
    list(GET fields 6 documentation)
    foreach(field_name kind source dependency owner rationale removal_condition documentation)
        string(STRIP "${${field_name}}" ${field_name})
        if("${${field_name}}" STREQUAL "")
            message(FATAL_ERROR
                "Module boundary allowlist entry has an empty ${field_name}: ${line}")
        endif()
    endforeach()

    if(NOT kind MATCHES "^(include|target-edge)$")
        message(FATAL_ERROR "Unsupported module boundary exception kind: ${kind}")
    endif()
    foreach(exact_field source dependency documentation)
        if("${${exact_field}}" MATCHES "[*?\[]" OR
           "${${exact_field}}" MATCHES "(^|/)[.][.](/|$)" OR
           "${${exact_field}}" MATCHES "^/")
            message(FATAL_ERROR
                "Module boundary allowlist ${exact_field} must be exact and repository-relative: ${${exact_field}}")
        endif()
    endforeach()
    if(kind STREQUAL "include")
        list(FIND classified_paths "${source}" classified_source_index)
        if(classified_source_index EQUAL -1)
            message(FATAL_ERROR "Module boundary include exception has an unclassified source: ${source}")
        endif()
    else()
        list(FIND module_targets "${source}" source_target_index)
        if(source_target_index EQUAL -1)
            message(FATAL_ERROR "Module boundary target exception has an unknown source target: ${source}")
        endif()
    endif()
    if(NOT documentation MATCHES "^docs/")
        message(FATAL_ERROR
            "Module boundary exception documentation must be an exact path under docs/: ${documentation}")
    endif()
    if(NOT EXISTS "${SOURCE_ROOT}/${documentation}")
        message(FATAL_ERROR "Module boundary exception documentation is missing: ${documentation}")
    endif()

    set(key "${kind}|${source}|${dependency}")
    list(FIND allowlist_keys "${key}" duplicate_key_index)
    if(NOT duplicate_key_index EQUAL -1)
        message(FATAL_ERROR "Duplicate module boundary allowlist entry: ${key}")
    endif()
    file(READ "${SOURCE_ROOT}/${documentation}" documentation_content)
    string(FIND "${documentation_content}" "${key}" documentation_key_position)
    if(documentation_key_position EQUAL -1)
        message(FATAL_ERROR
            "Module boundary exception is not documented with its exact key '${key}' in ${documentation}")
    endif()
    list(APPEND allowlist_keys "${key}")
endforeach()

set(failures "")
set(used_allowlist_keys "")

macro(handle_boundary_violation kind source dependency detail)
    set(violation_key "${kind}|${source}|${dependency}")
    list(FIND allowlist_keys "${violation_key}" allowlist_index)
    if(allowlist_index EQUAL -1)
        string(APPEND failures "\n  ${source}: ${detail}")
    else()
        list(APPEND used_allowlist_keys "${violation_key}")
    endif()
endmacro()

foreach(source_path IN LISTS classified_paths)
    module_owner_for_path("${source_path}" source_module)
    file(STRINGS "${SOURCE_ROOT}/${source_path}" include_lines
        REGEX "^[ \t]*#[ \t]*include[ \t]*[<\"][^>\"]+[>\"]")
    foreach(include_line IN LISTS include_lines)
        string(REGEX MATCH
            "^[ \t]*#[ \t]*include[ \t]*([<\"])([^>\"]+)[>\"]"
            include_match "${include_line}")
        set(include_delimiter "${CMAKE_MATCH_1}")
        set(include_token "${CMAKE_MATCH_2}")

        set(dependency_path "")
        if(include_token MATCHES "^noveltea/")
            set(dependency_path "engine/include/${include_token}")
            module_owner_for_path("${dependency_path}" dependency_module)
            if(dependency_module STREQUAL "")
                handle_boundary_violation(include "${source_path}" "${include_token}"
                    "NovelTea include '${include_token}' is not owned by a classified production module")
                continue()
            endif()
        elseif(include_delimiter STREQUAL "\"")
            cmake_path(GET source_path PARENT_PATH source_directory)
            set(include_candidates
                "${source_directory}/${include_token}"
                "engine/src/${include_token}"
                "engine/include/${include_token}")
            set(dependency_module "")
            foreach(candidate IN LISTS include_candidates)
                cmake_path(NORMAL_PATH candidate OUTPUT_VARIABLE normalized_candidate)
                module_owner_for_path("${normalized_candidate}" candidate_module)
                if(NOT candidate_module STREQUAL "")
                    set(dependency_path "${normalized_candidate}")
                    set(dependency_module "${candidate_module}")
                    break()
                endif()
            endforeach()
        else()
            set(dependency_module "")
        endif()

        if(NOT dependency_module STREQUAL "")
            module_dependency_allowed("${source_module}" "${dependency_module}" include_allowed)
            if(NOT include_allowed)
                handle_boundary_violation(include "${source_path}" "${include_token}"
                    "forbidden include '${include_token}' crosses from ${source_module} to ${dependency_module}")
            endif()
        else()
            external_include_family("${include_token}" include_family)
            if(NOT include_family STREQUAL "")
                external_include_allowed("${source_module}" "${include_family}" include_allowed)
                if(NOT include_allowed)
                    handle_boundary_violation(include "${source_path}" "${include_token}"
                        "forbidden ${include_family} include '${include_token}' in ${source_module}")
                endif()
            endif()
        endif()
    endforeach()
endforeach()

set(module_cmake_files "")
foreach(cmake_root CMakeLists.txt engine apps tools tests)
    if(cmake_root STREQUAL "CMakeLists.txt")
        if(EXISTS "${SOURCE_ROOT}/CMakeLists.txt")
            list(APPEND module_cmake_files "${SOURCE_ROOT}/CMakeLists.txt")
        endif()
    elseif(EXISTS "${SOURCE_ROOT}/${cmake_root}")
        file(GLOB_RECURSE discovered_cmake_files LIST_DIRECTORIES FALSE
            "${SOURCE_ROOT}/${cmake_root}/CMakeLists.txt"
            "${SOURCE_ROOT}/${cmake_root}/*.cmake")
        list(APPEND module_cmake_files ${discovered_cmake_files})
    endif()
endforeach()
list(REMOVE_DUPLICATES module_cmake_files)

foreach(cmake_file IN LISTS module_cmake_files)
    file(READ "${cmake_file}" cmake_content)
    string(REGEX REPLACE "#[^\n]*" "" cmake_content "${cmake_content}")
    set(remaining_content "${cmake_content}")
    while(TRUE)
        string(FIND "${remaining_content}" "target_link_libraries" command_position)
        if(command_position EQUAL -1)
            break()
        endif()
        string(SUBSTRING "${remaining_content}" ${command_position} -1 command_tail)
        string(FIND "${command_tail}" "(" open_position)
        if(open_position EQUAL -1)
            break()
        endif()
        math(EXPR body_start "${open_position} + 1")
        string(SUBSTRING "${command_tail}" ${body_start} -1 command_body_tail)
        string(FIND "${command_body_tail}" ")" close_position)
        if(close_position EQUAL -1)
            message(FATAL_ERROR "Unterminated target_link_libraries command in ${cmake_file}")
        endif()
        string(SUBSTRING "${command_body_tail}" 0 ${close_position} command_body)
        math(EXPR consumed "${body_start} + ${close_position} + 1")
        string(SUBSTRING "${command_tail}" ${consumed} -1 remaining_content)

        string(REGEX REPLACE "[ \t\r\n]+" ";" link_tokens "${command_body}")
        list(FILTER link_tokens EXCLUDE REGEX "^$")
        list(LENGTH link_tokens link_token_count)
        if(link_token_count LESS 1)
            continue()
        endif()
        list(GET link_tokens 0 source_target)
        list(FIND module_targets "${source_target}" source_target_index)
        if(source_target_index EQUAL -1)
            continue()
        endif()

        list(REMOVE_AT link_tokens 0)
        foreach(dependency_target IN LISTS link_tokens)
            if(dependency_target MATCHES "^(PRIVATE|PUBLIC|INTERFACE|LINK_PRIVATE|LINK_PUBLIC|debug|optimized|general)$")
                continue()
            endif()
            list(FIND module_targets "${dependency_target}" dependency_target_index)
            if(NOT dependency_target_index EQUAL -1)
                module_dependency_allowed("${source_target}" "${dependency_target}" target_allowed)
                if(NOT target_allowed)
                    handle_boundary_violation(target-edge "${source_target}" "${dependency_target}"
                        "forbidden target edge to ${dependency_target}")
                endif()
            elseif(source_target STREQUAL "noveltea_engine")
                continue()
            elseif(dependency_target MATCHES "^[$]<" OR
                   dependency_target MATCHES "^[$][{]")
                handle_boundary_violation(target-edge "${source_target}" "${dependency_target}"
                    "dynamic target edge '${dependency_target}' hides the dependency from policy validation")
            else()
                external_target_allowed("${source_target}" "${dependency_target}" target_allowed)
                if(NOT target_allowed)
                    handle_boundary_violation(target-edge "${source_target}" "${dependency_target}"
                        "forbidden external target edge to ${dependency_target}")
                endif()
            endif()
        endforeach()
    endwhile()
endforeach()

list(REMOVE_DUPLICATES used_allowlist_keys)
foreach(key IN LISTS allowlist_keys)
    list(FIND used_allowlist_keys "${key}" used_index)
    if(used_index EQUAL -1)
        message(FATAL_ERROR "Stale module boundary allowlist entry: ${key}")
    endif()
endforeach()

if(failures)
    message(FATAL_ERROR "Module boundary policy violations:${failures}")
endif()
