cmake_minimum_required(VERSION 3.24)

foreach(required SOURCE_ROOT CONTRACTS RULES EXCEPTIONS TEMPORARY_DEBT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()

get_filename_component(SOURCE_ROOT "${SOURCE_ROOT}" ABSOLUTE)
get_filename_component(CONTRACTS "${CONTRACTS}" ABSOLUTE)
get_filename_component(RULES "${RULES}" ABSOLUTE)
get_filename_component(EXCEPTIONS "${EXCEPTIONS}" ABSOLUTE)
get_filename_component(TEMPORARY_DEBT "${TEMPORARY_DEBT}" ABSOLUTE)

function(read_tsv path expected_columns out_var)
    file(STRINGS "${path}" lines ENCODING UTF-8)
    list(POP_FRONT lines header)
    set(records "")
    foreach(line IN LISTS lines)
        if(line STREQUAL "")
            continue()
        endif()
        string(REPLACE "\t" ";" fields "${line}")
        list(LENGTH fields count)
        if(NOT count EQUAL expected_columns)
            message(FATAL_ERROR "Malformed TSV record in ${path}: ${line}")
        endif()
        list(APPEND records "${line}")
    endforeach()
    set(${out_var} "${records}" PARENT_SCOPE)
endfunction()

function(validate_inventory_paths contract_id field_name paths_value)
    if(paths_value STREQUAL "")
        message(FATAL_ERROR "Inventory ${field_name} is empty for ${contract_id}")
    endif()
    string(REPLACE "," ";" paths "${paths_value}")
    foreach(path IN LISTS paths)
        if(NOT EXISTS "${SOURCE_ROOT}/${path}")
            message(FATAL_ERROR "Inventory ${field_name} path does not exist for ${contract_id}: ${path}")
        endif()
    endforeach()
endfunction()

function(validate_inventory_evidence contract_id field_name value paths_value)
    string(REPLACE "," ";" paths "${paths_value}")
    set(found FALSE)
    foreach(path IN LISTS paths)
        file(READ "${SOURCE_ROOT}/${path}" content)
        if(field_name STREQUAL "current version")
            if(content MATCHES "(^|[^0-9])${value}([^0-9]|$)")
                set(found TRUE)
                break()
            endif()
        else()
            string(FIND "${content}" "${value}" position)
            if(NOT position EQUAL -1)
                set(found TRUE)
                break()
            endif()
        endif()
    endforeach()
    if(NOT found)
        message(FATAL_ERROR
            "Inventory ${field_name} has no producer/consumer evidence for ${contract_id}: ${value}")
    endif()
endfunction()

read_tsv("${CONTRACTS}" 9 contract_records)
set(contract_ids "")
foreach(record IN LISTS contract_records)
    string(REPLACE "\t" ";" fields "${record}")
    list(GET fields 0 contract_id)
    list(GET fields 1 current_marker)
    list(GET fields 2 current_version)
    list(GET fields 3 owner)
    list(GET fields 4 producers)
    list(GET fields 5 consumers)
    list(GET fields 6 action)
    list(GET fields 7 positive_fixtures)
    list(GET fields 8 negative_fixtures)
    if(contract_id IN_LIST contract_ids)
        message(FATAL_ERROR "Duplicate contract_id: ${contract_id}")
    endif()
    list(APPEND contract_ids "${contract_id}")
    if(current_marker STREQUAL "")
        message(FATAL_ERROR "Inventory current_marker is empty for ${contract_id}")
    endif()
    if(NOT current_version MATCHES "^[1-9][0-9]*$")
        message(FATAL_ERROR "Inventory current_version is invalid for ${contract_id}: ${current_version}")
    endif()
    if(NOT owner MATCHES "^(build|editor|engine|editor\\+engine)$")
        message(FATAL_ERROR "Inventory owner is invalid for ${contract_id}: ${owner}")
    endif()
    if(NOT action MATCHES "^(reject|discard|regenerate)$")
        message(FATAL_ERROR "Invalid unsupported_input_action for ${contract_id}: ${action}")
    endif()
    validate_inventory_paths("${contract_id}" "producer" "${producers}")
    validate_inventory_paths("${contract_id}" "consumer" "${consumers}")
    validate_inventory_paths("${contract_id}" "positive fixture" "${positive_fixtures}")
    validate_inventory_paths("${contract_id}" "negative fixture" "${negative_fixtures}")
    set(evidence_paths "${producers},${consumers}")
    validate_inventory_evidence(
        "${contract_id}" "current marker" "${current_marker}" "${evidence_paths}")
    validate_inventory_evidence(
        "${contract_id}" "current version" "${current_version}" "${evidence_paths}")
endforeach()

read_tsv("${RULES}" 4 rule_records)
read_tsv("${EXCEPTIONS}" 4 exception_records)
read_tsv("${TEMPORARY_DEBT}" 5 debt_records)

set(allowance_keys "")
foreach(records_name exception_records debt_records)
    foreach(record IN LISTS ${records_name})
        string(REPLACE "\t" ";" fields "${record}")
        list(GET fields 0 rule_id)
        list(GET fields 1 path)
        list(GET fields 2 expected_count)
        if(NOT expected_count MATCHES "^[0-9]+$")
            message(FATAL_ERROR "Invalid expected count: ${record}")
        endif()
        string(MD5 key "${rule_id}|${path}")
        if(DEFINED allowance_${key})
            message(FATAL_ERROR "Duplicate debt/exception record: ${rule_id}|${path}")
        endif()
        list(APPEND allowance_keys "${key}")
        set(allowance_${key} "${expected_count}")
        set(allowance_label_${key} "${rule_id}|${path}")
        set(seen_${key} FALSE)
    endforeach()
endforeach()

foreach(record IN LISTS debt_records)
    string(REPLACE "\t" ";" fields "${record}")
    list(GET fields 3 phase)
    if(NOT phase MATCHES "^[2-7]$")
        message(FATAL_ERROR "Temporary debt must name active removal phase 2-7: ${record}")
    endif()
endforeach()

foreach(record IN LISTS rule_records)
    string(REPLACE "\t" ";" fields "${record}")
    list(GET fields 0 rule_id)
    list(GET fields 1 prefixes)
    list(GET fields 2 regex)
    string(REPLACE "," ";" prefixes "${prefixes}")
    set(files "")
    foreach(prefix IN LISTS prefixes)
        if(IS_DIRECTORY "${SOURCE_ROOT}/${prefix}")
            file(GLOB_RECURSE found LIST_DIRECTORIES FALSE "${SOURCE_ROOT}/${prefix}/*")
            list(APPEND files ${found})
        elseif(EXISTS "${SOURCE_ROOT}/${prefix}")
            list(APPEND files "${SOURCE_ROOT}/${prefix}")
        else()
            message(FATAL_ERROR "Rule path prefix does not exist: ${prefix}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES files)
    foreach(file IN LISTS files)
        file(RELATIVE_PATH relative "${SOURCE_ROOT}" "${file}")
        if(relative MATCHES "(^|/)(build|node_modules|refs|vcpkg_installed|dist-electron|out|\\.git)(/|$)" OR
           relative MATCHES "^docs/archive/" OR relative MATCHES "^android/.*/build/")
            continue()
        endif()
        file(READ "${file}" content)
        string(REGEX MATCHALL "${regex}" matches "${content}")
        list(LENGTH matches actual_count)
        if(actual_count GREATER 0)
            string(MD5 key "${rule_id}|${relative}")
            if(NOT DEFINED allowance_${key})
                message(FATAL_ERROR "Unlisted schema compatibility match: ${rule_id}|${relative} (${actual_count})")
            endif()
            if(NOT actual_count EQUAL allowance_${key})
                message(FATAL_ERROR "Wrong count for ${rule_id}|${relative}: expected ${allowance_${key}}, got ${actual_count}")
            endif()
            set(seen_${key} TRUE)
        endif()
    endforeach()
endforeach()

foreach(key IN LISTS allowance_keys)
    if(NOT seen_${key})
        message(FATAL_ERROR "Stale or unmatched schema-policy record: ${allowance_label_${key}}")
    endif()
endforeach()

message(STATUS "Schema version policy check passed")
