function(target_add_platform_sources target)
    cmake_parse_arguments(PARSE_ARGV 1 "" "" "" "LINUX;ANDROID;WEB;EMSCRIPTEN;ALL")

    foreach(src ${_ALL})
        target_sources(${target} PRIVATE ${src})
    endforeach()

    if(EMSCRIPTEN OR CMAKE_SYSTEM_NAME STREQUAL "Emscripten")
        foreach(src ${_WEB} ${_EMSCRIPTEN})
            target_sources(${target} PRIVATE ${src})
        endforeach()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
        foreach(src ${_ANDROID})
            target_sources(${target} PRIVATE ${src})
        endforeach()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        foreach(src ${_LINUX})
            target_sources(${target} PRIVATE ${src})
        endforeach()
    endif()
endfunction()

macro(check_vcpkg_target_pkg var pkg)
    if(NOT ${pkg}_FOUND)
        message(WARNING "${pkg} not found. ${var} features will be unavailable.")
    endif()
endmacro()
