option(NOVELTEA_ENABLE_SANITIZERS
    "Enable native AddressSanitizer and UndefinedBehaviorSanitizer instrumentation" OFF)
option(NOVELTEA_BUILD_FUZZERS "Build malformed-input parser fuzz targets" OFF)
option(NOVELTEA_USE_LIBFUZZER "Link parser fuzz targets with Clang libFuzzer" OFF)

if(NOVELTEA_ENABLE_SANITIZERS)
    if(EMSCRIPTEN OR CMAKE_SYSTEM_NAME STREQUAL "Android")
        message(FATAL_ERROR "NOVELTEA_ENABLE_SANITIZERS is a native desktop build mode")
    endif()

    if(MSVC)
        add_compile_options(/fsanitize=address /Oy-)
        add_link_options(/fsanitize=address)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        add_compile_options(-fsanitize=address,undefined -fno-omit-frame-pointer)
        add_link_options(-fsanitize=address,undefined -fno-omit-frame-pointer)
    else()
        message(FATAL_ERROR "Sanitizer mode is unsupported by ${CMAKE_CXX_COMPILER_ID}")
    endif()
endif()

if(NOVELTEA_USE_LIBFUZZER AND NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    message(FATAL_ERROR "NOVELTEA_USE_LIBFUZZER requires Clang")
endif()

function(noveltea_configure_fuzz_target target)
    noveltea_apply_runtime_compiler_policy("${target}")
    noveltea_apply_policy_warnings("${target}")
    if(NOVELTEA_USE_LIBFUZZER)
        target_compile_definitions("${target}" PRIVATE NOVELTEA_USE_LIBFUZZER=1)
        target_compile_options("${target}" PRIVATE -fsanitize=fuzzer)
        target_link_options("${target}" PRIVATE -fsanitize=fuzzer)
    endif()
endfunction()
