# Phase 5A primary ownership map for every production C/C++ source and header currently under
# engine/include and engine/src. This is classification data only; later Phase 5 subparts consume it
# when creating targets, moving files, and enforcing dependency policy.

set(NOVELTEA_MODULE_CLASSIFICATION_VERSION 1)

set(NOVELTEA_MODULE_CLASSIFICATION_TARGETS
    noveltea_domain
    noveltea_content
    noveltea_runtime
    noveltea_presentation
    noveltea_script_lua
    noveltea_engine
)

set(NOVELTEA_MODULE_FILES_noveltea_domain
    engine/include/noveltea/core/compiled_project.hpp
    engine/include/noveltea/core/compiler_policy.hpp
    engine/include/noveltea/core/diagnostic.hpp
    engine/include/noveltea/core/diagnostic_context.hpp
    engine/include/noveltea/core/domain_ids.hpp
    engine/include/noveltea/core/execution_primitives.hpp
    engine/include/noveltea/core/feature_state.hpp
    engine/include/noveltea/core/feature_view.hpp
    engine/include/noveltea/core/flow.hpp
    engine/include/noveltea/core/gameplay_pause.hpp
    engine/include/noveltea/core/layout_scale_policy.hpp
    engine/include/noveltea/core/loading_progress.hpp
    engine/include/noveltea/core/presentation_contracts.hpp
    engine/include/noveltea/core/presentation_operation_contracts.hpp
    engine/include/noveltea/core/property.hpp
    engine/include/noveltea/core/property_resolver.hpp
    engine/include/noveltea/core/result.hpp
    engine/include/noveltea/core/rich_text.hpp
    engine/include/noveltea/core/room_presentation_contracts.hpp
    engine/include/noveltea/core/runtime_diagnostic_context.hpp
    engine/include/noveltea/core/runtime_user_settings.hpp
    engine/include/noveltea/core/runtime_presentation_contracts.hpp
    engine/include/noveltea/core/runtime_value.hpp
    engine/include/noveltea/core/save_state.hpp
    engine/include/noveltea/core/save_state_codec_port.hpp
    engine/include/noveltea/core/session_operation_id.hpp
    engine/include/noveltea/core/session_state.hpp
    engine/include/noveltea/core/strong_id.hpp
    engine/include/noveltea/core/text_content.hpp
    engine/include/noveltea/core/typed_save_slot_id.hpp
    engine/include/noveltea/core/wait.hpp
    engine/include/noveltea/math/geometry.hpp
    engine/include/noveltea/render/material.hpp
    engine/include/noveltea/render/shader.hpp
    engine/src/core/compiled_project.cpp
    engine/src/core/compiled_project_validation.cpp
    engine/src/core/compiled_project_validation.hpp
    engine/src/core/diagnostic.cpp
    engine/src/core/gameplay_pause.cpp
    engine/src/core/property_resolver.cpp
    engine/src/core/rich_text.cpp
    engine/src/core/runtime_user_settings.cpp
    engine/src/core/save_state.cpp
    engine/src/core/session_state.cpp
    engine/src/render/material.cpp
)

set(NOVELTEA_MODULE_FILES_noveltea_content
    engine/include/noveltea/core/compiled_package.hpp
    engine/include/noveltea/core/compiled_package_codec.hpp
    engine/include/noveltea/core/compiled_project_codec.hpp
    engine/include/noveltea/core/editor_preview_contracts.hpp
    engine/include/noveltea/core/editor_protocol.hpp
    engine/include/noveltea/core/json_access.hpp
    engine/include/noveltea/core/package_export.hpp
    engine/include/noveltea/core/player_bootstrap.hpp
    engine/include/noveltea/core/rich_text_codec.hpp
    engine/include/noveltea/core/runtime_user_settings_codec.hpp
    engine/include/noveltea/core/save_state_codec.hpp
    engine/include/noveltea/render/material_codec.hpp
    engine/include/noveltea/render/shader_compiler.hpp
    engine/include/noveltea/render/shader_manifest.hpp
    engine/src/core/compiled_package.cpp
    engine/src/core/compiled_package_codec.cpp
    engine/src/core/compiled_project_codec/definitions_decoder.cpp
    engine/src/core/compiled_project_codec/dialogue_decoder.cpp
    engine/src/core/compiled_project_codec/interaction_decoder.cpp
    engine/src/core/compiled_project_codec/internal.hpp
    engine/src/core/compiled_project_codec/linker.cpp
    engine/src/core/compiled_project_codec/project_decoder.cpp
    engine/src/core/compiled_project_codec/project_fields.cpp
    engine/src/core/compiled_project_codec/scene_decoder.cpp
    engine/src/core/compiled_project_codec/shared_values.cpp
    engine/src/core/compiled_project_wire.hpp
    engine/src/core/editor_protocol.cpp
    engine/src/core/package_export.cpp
    engine/src/core/player_bootstrap.cpp
    engine/src/core/rich_text_codec.cpp
    engine/src/core/runtime_user_settings_codec.cpp
    engine/src/core/save_state_codec.cpp
    engine/src/core/save_state_codec/codec_internal.hpp
    engine/src/core/save_state_codec/flow_codec.cpp
    engine/src/core/save_state_codec/presentation_codec.cpp
    engine/src/core/save_state_codec/shared_values.cpp
    engine/src/core/save_state_codec/state_codec.cpp
    engine/src/core/save_state_codec/validation.cpp
    engine/src/render/material_codec.cpp
    engine/src/render/shader_compiler.cpp
    engine/src/render/shader_manifest.cpp
)

set(NOVELTEA_MODULE_FILES_noveltea_runtime
    engine/include/noveltea/core/checkpoint_contracts.hpp
    engine/include/noveltea/core/flow_executor.hpp
    engine/include/noveltea/core/runtime_capability_types.hpp
    engine/include/noveltea/core/runtime_clock.hpp
    engine/include/noveltea/core/runtime_messages.hpp
    engine/include/noveltea/core/runtime_shell_contracts.hpp
    engine/include/noveltea/core/shared_evaluator.hpp
    engine/include/noveltea/core/typed_save_slot_store.hpp
    engine/include/noveltea/runtime/running_game.hpp
    engine/include/noveltea/runtime/runtime_capabilities.hpp
    engine/include/noveltea/runtime/runtime_checkpoint_service.hpp
    engine/include/noveltea/runtime/runtime_command_gateway.hpp
    engine/include/noveltea/runtime/runtime_commands.hpp
    engine/include/noveltea/runtime/runtime_contracts.hpp
    engine/include/noveltea/runtime/runtime_executor.hpp
    engine/include/noveltea/runtime/runtime_identity.hpp
    engine/include/noveltea/runtime/runtime_ports.hpp
    engine/include/noveltea/runtime/runtime_session.hpp
    engine/src/runtime/flow_executor.cpp
    engine/src/runtime/flow_executor_blockers.cpp
    engine/src/runtime/flow_executor_dialogue.cpp
    engine/src/runtime/flow_executor_interaction.cpp
    engine/src/runtime/flow_executor_room.cpp
    engine/src/runtime/flow_executor_scene.cpp
    engine/src/runtime/runtime_clock.cpp
    engine/src/runtime/session_restore.cpp
    engine/src/runtime/shared_evaluator.cpp
    engine/src/runtime/typed_save_slot_store.cpp
    engine/src/runtime/running_game.cpp
    engine/src/runtime/runtime_checkpoint_service.cpp
    engine/src/runtime/runtime_command_gateway.cpp
    engine/src/runtime/runtime_executor.cpp
    engine/src/runtime/runtime_executor_dialogue.cpp
    engine/src/runtime/runtime_executor_interaction.cpp
    engine/src/runtime/runtime_executor_map.cpp
    engine/src/runtime/runtime_executor_room.cpp
    engine/src/runtime/runtime_session.cpp
)

set(NOVELTEA_MODULE_FILES_noveltea_presentation
    engine/include/noveltea/presentation/runtime_presentation_model.hpp
    engine/include/noveltea/presentation/presentation_coordinator.hpp
    engine/include/noveltea/presentation/presentation_operation_requests.hpp
    engine/include/noveltea/presentation/room_presentation.hpp
    engine/include/noveltea/presentation/runtime_presentation.hpp
    engine/include/noveltea/presentation/runtime_layout_manager.hpp
    engine/include/noveltea/presentation/runtime_system_layouts.hpp
    engine/src/presentation/presentation_coordinator.cpp
    engine/src/presentation/presentation_operation_requests.cpp
    engine/src/presentation/room_presentation.cpp
    engine/src/presentation/runtime_presentation.cpp
    engine/src/presentation/runtime_presentation_model.cpp
    engine/src/presentation/runtime_layout_manager.cpp
    engine/src/presentation/runtime_system_layouts.cpp
)

set(NOVELTEA_MODULE_FILES_noveltea_script_lua
    engine/include/noveltea/script/runtime_script_api.hpp
    engine/include/noveltea/script/script_result.hpp
    engine/include/noveltea/script/script_runtime.hpp
    engine/include/noveltea/script/script_value.hpp
    engine/src/script/lua/bind_noveltea.cpp
    engine/src/script/lua/bind_runtime_capabilities.cpp
    engine/src/script/lua/bind_typed_script_host.cpp
    engine/src/script/lua/script_runtime.cpp
    engine/src/script/lua/script_runtime_internal.hpp
    engine/src/script/lua/sol_access.hpp
    engine/src/script/lua/runtime_script_api.cpp
)

set(NOVELTEA_MODULE_FILES_noveltea_engine
    engine/include/noveltea/active_text.hpp
    engine/include/noveltea/active_text_layout.hpp
    engine/include/noveltea/active_text_playback.hpp
    engine/include/noveltea/animation/tween_service.hpp
    engine/include/noveltea/assets/asset_manager.hpp
    engine/include/noveltea/assets/asset_cache_keys.hpp
    engine/include/noveltea/assets/asset_path.hpp
    engine/include/noveltea/assets/asset_request.hpp
    engine/include/noveltea/assets/asset_request_orchestrator.hpp
    engine/include/noveltea/assets/asset_residency.hpp
    engine/include/noveltea/assets/asset_source.hpp
    engine/include/noveltea/assets/assets.hpp
    engine/include/noveltea/assets/resource_aliases.hpp
    engine/include/noveltea/assets/typed_assets.hpp
    engine/include/noveltea/audio/audio_backend.hpp
    engine/include/noveltea/audio/audio_system.hpp
    engine/include/noveltea/audio/audio_types.hpp
    engine/include/noveltea/boundary/running_game_loader.hpp
    engine/include/noveltea/core/asset_telemetry.hpp
    engine/include/noveltea/core/editor_runtime_protocol.hpp
    engine/include/noveltea/engine.hpp
    engine/include/noveltea/engine_tooling.hpp
    engine/include/noveltea/jobs/job_completion_queue.hpp
    engine/include/noveltea/jobs/job_clock.hpp
    engine/include/noveltea/jobs/cooperative_job_executor.hpp
    engine/include/noveltea/jobs/job_executor.hpp
    engine/include/noveltea/jobs/inline_job_executor.hpp
    engine/include/noveltea/jobs/sdl_thread_pool_job_executor.hpp
    engine/include/noveltea/jobs/job_types.hpp
    engine/include/noveltea/jobs/owner_thread.hpp
    engine/include/noveltea/platform.hpp
    engine/include/noveltea/platform/input_event.hpp
    engine/include/noveltea/platform/window_event.hpp
    engine/include/noveltea/preview_bridge.hpp
    engine/include/noveltea/render/quad_batch.hpp
    engine/include/noveltea/render/rasterization_policy.hpp
    engine/include/noveltea/render/renderer_backend.hpp
    engine/include/noveltea/render/resources.hpp
    engine/include/noveltea/render/texture.hpp
    engine/include/noveltea/renderer.hpp
    engine/include/noveltea/runtime_audio_adapter.hpp
    engine/include/noveltea/runtime_presentation_bridge.hpp
    engine/include/noveltea/runtime_preview_controller.hpp
    engine/include/noveltea/runtime_ui_contracts.hpp
    engine/include/noveltea/surface.hpp
    engine/include/noveltea/text/font.hpp
    engine/include/noveltea/text/text.hpp
    engine/include/noveltea/text/text_asset_loader.hpp
    engine/include/noveltea/text/text_buffer.hpp
    engine/include/noveltea/text/text_lab.hpp
    engine/include/noveltea/text/text_layout.hpp
    engine/include/noveltea/text/text_renderer.hpp
    engine/include/noveltea/text/text_style.hpp
    engine/include/noveltea/world_presentation.hpp
    engine/include/noveltea/world_transition.hpp
    engine/src/active_text.cpp
    engine/src/active_text_layout.cpp
    engine/src/active_text_playback.cpp
    engine/src/animation/tween_service.cpp
    engine/src/assets.cpp
    engine/src/assets/asset_manager.cpp
    engine/src/assets/asset_preparation_io.hpp
    engine/src/assets/asset_residency_manager.cpp
    engine/src/assets/resource_aliases.cpp
    engine/src/assets/zip_asset_source.cpp
    engine/src/audio/audio_system.cpp
    engine/src/audio/miniaudio/miniaudio_backend.cpp
    engine/src/boundary/running_game_loader.cpp
    engine/src/devtools/debug_ui.hpp
    engine/src/core/editor_runtime_protocol.cpp
    engine/src/devtools/imgui_bgfx.cpp
    engine/src/devtools/imgui_bgfx.hpp
    engine/src/engine.cpp
    engine/src/host/audio_preview_adapter.cpp
    engine/src/host/audio_preview_adapter.hpp
    engine/src/host/debug_ui_command_executor.cpp
    engine/src/host/debug_ui_command_executor.hpp
    engine/src/host/debug_ui_contracts.hpp
    engine/src/host/engine_impl.hpp
    engine/src/host/game_host.cpp
    engine/src/host/game_host.hpp
    engine/src/host/host_input_router.cpp
    engine/src/host/host_input_router.hpp
    engine/src/host/host_lifecycle_contracts.hpp
    engine/src/host/layout_composition.hpp
    engine/src/host/layout_realization_contracts.hpp
    engine/src/host/layout_realizer.cpp
    engine/src/host/layout_realizer.hpp
    engine/src/host/job_executor_bootstrap.cpp
    engine/src/host/job_executor_bootstrap.hpp
    engine/src/host/presentation_layout_reconciler.cpp
    engine/src/host/presentation_layout_reconciler.hpp
    engine/src/host/preview_host.cpp
    engine/src/host/preview_host.hpp
    engine/src/host/preview_host_contracts.hpp
    engine/src/host/runtime_host_contracts.hpp
    engine/src/host/runtime_ui_asset_service.hpp
    engine/src/host/runtime_ui_host.hpp
    engine/src/host/screenshot_capture.cpp
    engine/src/host/screenshot_capture.hpp
    engine/src/jobs/cooperative_job_executor.cpp
    engine/src/jobs/inline_job_executor.cpp
    engine/src/jobs/sdl_thread_pool_job_executor.cpp
    engine/src/jobs/scheduler_core.cpp
    engine/src/jobs/scheduler_core.hpp
    engine/src/platform/sdl/sdl_platform.cpp
    engine/src/platform/sdl/sdl_platform.hpp
    engine/src/preview/preview_bridge.cpp
    engine/src/render/rasterization_policy.cpp
    engine/src/render/bgfx/bgfx_material_binder.cpp
    engine/src/render/bgfx/bgfx_material_binder.hpp
    engine/src/render/bgfx/bgfx_quad_batch.cpp
    engine/src/render/bgfx/bgfx_renderer.cpp
    engine/src/render/bgfx/bgfx_renderer_internal.hpp
    engine/src/render/bgfx/bgfx_screenshot_capture.cpp
    engine/src/render/bgfx/bgfx_screenshot_capture.hpp
    engine/src/render/bgfx/bgfx_resources.cpp
    engine/src/render/bgfx/bgfx_shader_loader.cpp
    engine/src/render/bgfx/bgfx_shader_loader.hpp
    engine/src/render/bgfx/bgfx_shader_program_cache.cpp
    engine/src/render/bgfx/bgfx_shader_program_cache.hpp
    engine/src/render/bgfx/bgfx_typed_asset_loader.cpp
    engine/src/render/bgfx/bgfx_typed_asset_loader.hpp
    engine/src/render/bgfx/text/bgfx_text_renderer.cpp
    engine/src/runtime_audio_adapter.cpp
    engine/src/runtime_presentation_bridge.cpp
    engine/src/runtime_preview_controller.cpp
    engine/src/host/runtime_ui_asset_service.cpp
    engine/src/surface.cpp
    engine/src/text/text_asset_loader.cpp
    engine/src/text/text_breaks.cpp
    engine/src/text/text_breaks.hpp
    engine/src/text/text_engine.cpp
    engine/src/text/text_engine.hpp
    engine/src/text/text_layout.cpp
    engine/src/ui/rmlui/active_text_presenter.cpp
    engine/src/ui/rmlui/active_text_presenter.hpp
    engine/src/ui/rmlui/rmlui_bgfx_noveltea_adapter.cpp
    engine/src/ui/rmlui/rmlui_custom_components.cpp
    engine/src/ui/rmlui/rmlui_custom_components.hpp
    engine/src/ui/rmlui/rmlui_document_binder.cpp
    engine/src/ui/rmlui/rmlui_document_binder.hpp
    engine/src/ui/rmlui/rmlui_document_registry.cpp
    engine/src/ui/rmlui/rmlui_document_registry.hpp
    engine/src/ui/rmlui/rmlui_event_disposition.hpp
    engine/src/ui/rmlui/rmlui_file_interface.cpp
    engine/src/ui/rmlui/rmlui_file_interface.hpp
    engine/src/ui/rmlui/rmlui_host.cpp
    engine/src/ui/rmlui/rmlui_host.hpp
    engine/src/ui/rmlui/rmlui_host_frame.cpp
    engine/src/ui/rmlui/rmlui_host_input.cpp
    engine/src/ui/rmlui/rmlui_host_input.hpp
    engine/src/ui/rmlui/rmlui_input_sdl3.cpp
    engine/src/ui/rmlui/rmlui_input_sdl3.hpp
    engine/src/ui/rmlui/rmlui_lifecycle.hpp
    engine/src/ui/rmlui/rmlui_render_interface_bgfx.hpp
    engine/src/ui/rmlui/rmlui_system_interface_sdl3.cpp
    engine/src/ui/rmlui/rmlui_system_interface_sdl3.hpp
    engine/src/ui/rmlui/rmlui_template_resolver.cpp
    engine/src/ui/rmlui/rmlui_template_resolver.hpp
    engine/src/ui/rmlui/runtime_ui_binder.cpp
    engine/src/ui/rmlui/runtime_ui_binder.hpp
    engine/src/ui/rmlui/runtime_ui_facade_access.hpp
    engine/src/ui/rmlui/runtime_ui_playback_driver.cpp
    engine/src/ui/rmlui/runtime_ui_playback_driver.hpp
    engine/src/ui/rmlui/runtime_ui.hpp
    engine/src/ui_debug_imgui.cpp
    engine/src/ui_debug_stub.cpp
    engine/src/ui/rmlui/runtime_ui.cpp
    engine/src/world_presentation.cpp
    engine/src/world_transition.cpp
)
