cmake_minimum_required(VERSION 3.25)
foreach(required NOVELTEA_TEMPLATE_PRESET NOVELTEA_TEMPLATE_PLATFORM NOVELTEA_TEMPLATE_ARCH NOVELTEA_RELEASE_TAG)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} is required")
  endif()
endforeach()
set(root "${CMAKE_CURRENT_LIST_DIR}/..")
cmake_path(ABSOLUTE_PATH root NORMALIZE OUTPUT_VARIABLE root)
set(build "${root}/build/${NOVELTEA_TEMPLATE_PRESET}")
set(stage "${root}/build/package/noveltea-player-${NOVELTEA_TEMPLATE_PLATFORM}-${NOVELTEA_TEMPLATE_ARCH}-release")
set(dist "${root}/dist")
file(REMOVE_RECURSE "${stage}")
file(MAKE_DIRECTORY "${stage}/bin" "${stage}/assets" "${stage}/licenses")
if(NOVELTEA_TEMPLATE_PLATFORM STREQUAL "windows")
  set(player "${build}/apps/player/noveltea-player.exe")
  set(executable_name "noveltea-player.exe")
  set(graphics "direct3d11")
  set(minimum "Windows 10 1809")
  set(extension "zip")
elseif(NOVELTEA_TEMPLATE_PLATFORM STREQUAL "macos")
  set(player "${build}/apps/player/noveltea-player")
  set(executable_name "noveltea-player")
  set(graphics "metal")
  set(minimum "macOS 13")
  set(extension "tar.gz")
else()
  set(player "${build}/apps/player/noveltea-player")
  set(executable_name "noveltea-player")
  set(graphics "opengl")
  set(minimum "Ubuntu 22.04 / glibc 2.35")
  set(extension "tar.gz")
endif()
if(NOT EXISTS "${player}")
  message(FATAL_ERROR "Missing player executable: ${player}")
endif()
file(COPY_FILE "${player}" "${stage}/bin/${executable_name}")
file(CHMOD "${stage}/bin/${executable_name}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
if(NOVELTEA_TEMPLATE_PLATFORM STREQUAL "windows")
  file(GLOB player_runtime_dlls "${build}/apps/player/*.dll")
  foreach(runtime_dll IN LISTS player_runtime_dlls)
    file(COPY "${runtime_dll}" DESTINATION "${stage}/bin")
  endforeach()
endif()
if(IS_DIRECTORY "${build}/runtime-assets/system")
  file(COPY "${build}/runtime-assets/system" DESTINATION "${stage}/assets")
endif()
find_program(NODE_EXECUTABLE node REQUIRED)
execute_process(COMMAND "${NODE_EXECUTABLE}" "${root}/cmake/generate-player-template-metadata.mjs" "${build}/vcpkg_installed" "${stage}" "${NOVELTEA_RELEASE_TAG}" COMMAND_ERROR_IS_FATAL ANY)

if(NOVELTEA_TEMPLATE_PLATFORM STREQUAL "windows")
  set(player_pdb "${build}/apps/player/noveltea-player.pdb")
  if(NOT EXISTS "${player_pdb}")
    message(FATAL_ERROR "Missing build-ID-matched Windows player symbols: ${player_pdb}")
  endif()
  file(MAKE_DIRECTORY "${stage}/symbols")
  file(COPY_FILE "${player_pdb}" "${stage}/symbols/noveltea-player.pdb")
endif()

file(GLOB_RECURSE staged_files RELATIVE "${stage}" "${stage}/*")
list(SORT staged_files)
set(file_entries "")
set(dependency_entries "")
set(windows_imports_json "")
if(NOVELTEA_TEMPLATE_PLATFORM STREQUAL "windows")
  find_program(DUMPBIN dumpbin REQUIRED)
  execute_process(COMMAND "${DUMPBIN}" /DEPENDENTS "${player}" OUTPUT_VARIABLE dumpbin_dependencies COMMAND_ERROR_IS_FATAL ANY)
  string(REGEX MATCHALL "[A-Za-z0-9_.-]+\\.[dD][lL][lL]" windows_imports "${dumpbin_dependencies}")
  list(REMOVE_DUPLICATES windows_imports)
  list(SORT windows_imports)
  foreach(import IN LISTS windows_imports)
    string(TOLOWER "${import}" import_lower)
    if(NOT windows_imports_json STREQUAL "")
      string(APPEND windows_imports_json ",")
    endif()
    string(APPEND windows_imports_json "\"${import_lower}\"")
  endforeach()
endif()
foreach(relative IN LISTS staged_files)
  if(IS_DIRECTORY "${stage}/${relative}")
    continue()
  endif()
  file(SIZE "${stage}/${relative}" size)
  file(SHA256 "${stage}/${relative}" hash)
  if(relative STREQUAL "bin/${executable_name}")
    set(mode 493)
    set(kind library)
    set(role player)
  elseif(relative MATCHES "^symbols/.*\\.pdb$")
    set(mode 420)
    set(kind asset)
    set(role symbol)
  elseif(relative MATCHES "^licenses/")
    set(mode 420)
    set(kind notice)
    set(role notice)
  elseif(relative MATCHES "\\.dll$")
    set(mode 420)
    set(kind library)
    set(role native-dependency)
  elseif(relative MATCHES "^assets/")
    set(mode 420)
    set(kind asset)
    set(role system-asset)
  else()
    set(mode 420)
    set(kind asset)
    set(role support)
  endif()
  if(NOT file_entries STREQUAL "")
    string(APPEND file_entries ",")
  endif()
  string(APPEND file_entries "{\"path\":\"${relative}\",\"size\":${size},\"mode\":${mode},\"sha256\":\"${hash}\",\"role\":\"${role}\"}")
  if(kind STREQUAL "library" OR kind STREQUAL "notice")
    if(NOT dependency_entries STREQUAL "")
      string(APPEND dependency_entries ",")
    endif()
    string(APPEND dependency_entries "{\"path\":\"${relative}\",\"kind\":\"${kind}\"}")
  endif()
endforeach()
set(template_id "${NOVELTEA_TEMPLATE_PLATFORM}-${NOVELTEA_TEMPLATE_ARCH}-release")
set(build_id "${NOVELTEA_RELEASE_TAG}-${NOVELTEA_TEMPLATE_PLATFORM}-${NOVELTEA_TEMPLATE_ARCH}-release")
set(archive_name "noveltea-player-template-${NOVELTEA_RELEASE_TAG}-${NOVELTEA_TEMPLATE_PLATFORM}-${NOVELTEA_TEMPLATE_ARCH}-release.${extension}")
set(symbol_name "noveltea-player-symbols-${NOVELTEA_RELEASE_TAG}-${NOVELTEA_TEMPLATE_PLATFORM}-${NOVELTEA_TEMPLATE_ARCH}-release.${extension}")
set(windows_descriptor_fields "")
if(NOVELTEA_TEMPLATE_PLATFORM STREQUAL "windows")
  set(windows_descriptor_fields ",\"windowsImports\":[${windows_imports_json}]")
endif()
file(WRITE "${stage}/template.json" "{\"format\":\"noveltea.player-template\",\"formatVersion\":1,\"templateId\":\"${template_id}\",\"buildId\":\"${build_id}\",\"engineVersion\":\"${NOVELTEA_RELEASE_TAG}\",\"platform\":\"${NOVELTEA_TEMPLATE_PLATFORM}\",\"architecture\":\"${NOVELTEA_TEMPLATE_ARCH}\",\"minimumPlatformVersion\":\"${minimum}\",\"graphicsBackends\":[\"${graphics}\"],\"shaderVariants\":[\"glsl-120\",\"essl-100\",\"essl-300\"],\"runtimePackageApi\":{\"minimum\":1,\"maximum\":1},\"playerConfigApi\":{\"minimum\":1,\"maximum\":1},\"compiledFeatures\":[\"lua\",\"rmlui\",\"audio\",\"save\"],\"capabilities\":[\"network.client\",\"external-url\",\"clipboard.read\",\"clipboard.write\",\"gamepad\"],\"buildFlavor\":\"release\",\"packageAccessModes\":[\"sidecar\",\"bundle-resource\"],\"files\":[${file_entries}],\"runtimeDependencies\":[${dependency_entries}]${windows_descriptor_fields},\"artifacts\":{\"archive\":\"${archive_name}\",\"symbols\":\"${symbol_name}\",\"sbom\":\"SBOM.cdx.json\",\"notices\":\"licenses/THIRD_PARTY_NOTICES.txt\"},\"provenance\":{\"provider\":\"github-attestation\",\"source\":\"${NOVELTEA_RELEASE_TAG}\"},\"host\":{\"assembly\":\"any\",\"requiresToolchain\":false,\"tools\":[]}}\n")
file(MAKE_DIRECTORY "${dist}")
get_filename_component(stage_parent "${stage}" DIRECTORY)
get_filename_component(stage_name "${stage}" NAME)
if(extension STREQUAL "zip")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${dist}/${archive_name}" --format=zip "${stage_name}" WORKING_DIRECTORY "${stage_parent}" COMMAND_ERROR_IS_FATAL ANY)
else()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar czf "${dist}/${archive_name}" "${stage_name}" WORKING_DIRECTORY "${stage_parent}" COMMAND_ERROR_IS_FATAL ANY)
endif()
file(MAKE_DIRECTORY "${stage_parent}/symbols-${build_id}")
file(WRITE "${stage_parent}/symbols-${build_id}/BUILD_ID" "${build_id}\n")
if(NOVELTEA_TEMPLATE_PLATFORM STREQUAL "linux")
  find_program(OBJCOPY objcopy REQUIRED)
  execute_process(COMMAND "${OBJCOPY}" --only-keep-debug "${player}" "${stage_parent}/symbols-${build_id}/noveltea-player.debug" COMMAND_ERROR_IS_FATAL ANY)
elseif(NOVELTEA_TEMPLATE_PLATFORM STREQUAL "macos")
  find_program(DSYMUTIL dsymutil REQUIRED)
  execute_process(COMMAND "${DSYMUTIL}" "${player}" -o "${stage_parent}/symbols-${build_id}/noveltea-player.dSYM" COMMAND_ERROR_IS_FATAL ANY)
elseif(NOVELTEA_TEMPLATE_PLATFORM STREQUAL "windows")
  file(COPY_FILE "${player_pdb}" "${stage_parent}/symbols-${build_id}/noveltea-player.pdb")
else()
  message(FATAL_ERROR "Unsupported player-template platform for symbol packaging: ${NOVELTEA_TEMPLATE_PLATFORM}")
endif()
if(extension STREQUAL "zip")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${dist}/${symbol_name}" --format=zip "symbols-${build_id}" WORKING_DIRECTORY "${stage_parent}" COMMAND_ERROR_IS_FATAL ANY)
else()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar czf "${dist}/${symbol_name}" "symbols-${build_id}" WORKING_DIRECTORY "${stage_parent}" COMMAND_ERROR_IS_FATAL ANY)
endif()
file(COPY_FILE "${stage}/template.json" "${dist}/${template_id}.template.json")
file(COPY_FILE "${stage}/SBOM.cdx.json" "${dist}/${template_id}.SBOM.cdx.json")
file(COPY_FILE "${stage}/licenses/THIRD_PARTY_NOTICES.txt" "${dist}/${template_id}.THIRD_PARTY_NOTICES.txt")
