cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED NOVELTEA_PACKAGE_KIND OR NOT DEFINED NOVELTEA_RELEASE_TAG)
    message(FATAL_ERROR "Set NOVELTEA_PACKAGE_KIND and NOVELTEA_RELEASE_TAG")
endif()

set(root "${CMAKE_CURRENT_LIST_DIR}/..")
cmake_path(ABSOLUTE_PATH root NORMALIZE OUTPUT_VARIABLE root)
set(dist "${root}/dist")
set(build_type "$ENV{NOVELTEA_RELEASE_BUILD_TYPE}")
if(build_type STREQUAL "")
    set(build_type "release")
endif()
set(platform "$ENV{NOVELTEA_RELEASE_PLATFORM}")
set(arch "$ENV{NOVELTEA_RELEASE_ARCH}")
if(arch STREQUAL "")
    set(arch "x64")
endif()

file(MAKE_DIRECTORY "${dist}")

function(require_file path)
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        message(FATAL_ERROR "Missing required file: ${path}")
    endif()
endfunction()

function(require_dir path)
    if(NOT IS_DIRECTORY "${path}")
        message(FATAL_ERROR "Missing required directory: ${path}")
    endif()
endfunction()

function(archive_dir source_dir output)
    get_filename_component(parent "${source_dir}" DIRECTORY)
    get_filename_component(name "${source_dir}" NAME)
    file(REMOVE "${output}")
    if(output MATCHES "\\.zip$")
        execute_process(
            COMMAND "${CMAKE_COMMAND}" -E tar cf "${output}" --format=zip "${name}"
            WORKING_DIRECTORY "${parent}"
            COMMAND_ERROR_IS_FATAL ANY)
    else()
        execute_process(
            COMMAND "${CMAKE_COMMAND}" -E tar czf "${output}" "${name}"
            WORKING_DIRECTORY "${parent}"
            COMMAND_ERROR_IS_FATAL ANY)
    endif()
endfunction()

function(package_sandbox preset exe_name extension)
    if(platform STREQUAL "")
        message(FATAL_ERROR "NOVELTEA_RELEASE_PLATFORM is required for sandbox packages")
    endif()
    set(bundle "${root}/build/package/noveltea-sandbox-${platform}-${arch}-${build_type}")
    file(REMOVE_RECURSE "${bundle}")
    file(MAKE_DIRECTORY "${bundle}/assets")
    set(exe "${root}/build/${preset}/apps/sandbox/${exe_name}")
    set(assets "${root}/build/${preset}/runtime-assets")
    require_file("${exe}")
    require_dir("${assets}")
    file(COPY "${exe}" DESTINATION "${bundle}")
    file(COPY "${assets}/" DESTINATION "${bundle}/assets")
    require_file("${bundle}/assets/system/shaders/bgfx/glsl-120/triangle.vs.bin")
    require_file("${bundle}/assets/system/ui/title/default-title.rml")
    require_file("${bundle}/assets/system/ui/runtime/runtime_game.rml")
    require_file("${bundle}/assets/system/ui/menu/pause-menu.rml")
    require_file("${bundle}/assets/system/ui/menu/pause-menu.rcss")
    require_file("${bundle}/assets/project/rmlui/lua_demo.rml")
    require_file("${bundle}/assets/project/rmlui/lua_demo.lua")
    set(output "${dist}/noveltea-sandbox-${NOVELTEA_RELEASE_TAG}-${platform}-${arch}-${build_type}.${extension}")
    archive_dir("${bundle}" "${output}")
endfunction()

if(NOVELTEA_PACKAGE_KIND STREQUAL "desktop-sandbox")
    if(platform STREQUAL "linux")
        package_sandbox("linux-release" "noveltea-sandbox" "tar.gz")
    elseif(platform STREQUAL "windows")
        package_sandbox("windows-release" "noveltea-sandbox.exe" "zip")
    elseif(platform STREQUAL "macos")
        package_sandbox("macos-release" "noveltea-sandbox" "zip")
    else()
        message(FATAL_ERROR "Unsupported desktop sandbox platform: ${platform}")
    endif()
elseif(NOVELTEA_PACKAGE_KIND STREQUAL "web")
    set(bundle "${root}/build/package/noveltea-sandbox-web-wasm32-${build_type}")
    file(REMOVE_RECURSE "${bundle}")
    file(MAKE_DIRECTORY "${bundle}")
    foreach(file_name index.html index.js index.wasm index.data)
        require_file("${root}/build/web-release/apps/sandbox/${file_name}")
        file(COPY "${root}/build/web-release/apps/sandbox/${file_name}" DESTINATION "${bundle}")
    endforeach()
    file(READ "${bundle}/index.js" index_js)
    if(NOT index_js MATCHES "/assets/project/rmlui/lua_demo\\.rml" OR NOT index_js MATCHES "/assets/project/rmlui/lua_demo\\.lua")
        message(FATAL_ERROR "Web bundle is missing RmlUi/Lua demo preload references")
    endif()
    archive_dir("${bundle}" "${dist}/noveltea-sandbox-${NOVELTEA_RELEASE_TAG}-web-wasm32-${build_type}.tar.gz")
elseif(NOVELTEA_PACKAGE_KIND STREQUAL "android")
    set(flavor "$ENV{NOVELTEA_ANDROID_RELEASE_FLAVOR}")
    if(flavor STREQUAL "")
        set(flavor "unsigned-internal")
    endif()
    set(apk "${root}/android/app/build/outputs/apk/release/app-release.apk")
    if(NOT EXISTS "${apk}")
        set(apk "${root}/android/app/build/outputs/apk/release/app-release-unsigned.apk")
    endif()
    require_file("${apk}")
    execute_process(COMMAND unzip -l "${apk}" OUTPUT_VARIABLE apk_listing COMMAND_ERROR_IS_FATAL ANY)
    if(NOT apk_listing MATCHES "assets/system/shaders/bgfx/essl-300/triangle\\.vs\\.bin" OR NOT apk_listing MATCHES "assets/system/ui/title/default-title\\.rml" OR NOT apk_listing MATCHES "assets/system/ui/runtime/runtime_game\\.rml" OR NOT apk_listing MATCHES "assets/system/ui/menu/pause-menu\\.rml" OR NOT apk_listing MATCHES "assets/project/rmlui/lua_demo\\.rml")
        message(FATAL_ERROR "Android APK is missing required runtime assets")
    endif()
    file(COPY_FILE "${apk}" "${dist}/noveltea-sandbox-${NOVELTEA_RELEASE_TAG}-android-universal-${build_type}-${flavor}.apk")
elseif(NOVELTEA_PACKAGE_KIND STREQUAL "desktop-editor")
    if(platform STREQUAL "")
        message(FATAL_ERROR "NOVELTEA_RELEASE_PLATFORM is required for editor packages")
    endif()
    set(pointer "${root}/editor/out/electron-builder/latest-artifact.json")
    require_file("${pointer}")
    file(READ "${pointer}" pointer_json)
    string(JSON pointer_release_tag GET "${pointer_json}" releaseTag)
    string(JSON pointer_platform GET "${pointer_json}" platform)
    string(JSON pointer_arch GET "${pointer_json}" architecture)
    string(JSON output_root GET "${pointer_json}" outputRoot)
    string(JSON artifact_count LENGTH "${pointer_json}" artifacts)
    if(NOT "${pointer_release_tag}" STREQUAL "${NOVELTEA_RELEASE_TAG}")
        message(FATAL_ERROR "Editor artifact release tag mismatch: expected ${NOVELTEA_RELEASE_TAG}, found ${pointer_release_tag}")
    endif()
    if(NOT "${pointer_platform}" STREQUAL "${platform}" OR NOT "${pointer_arch}" STREQUAL "${arch}")
        message(FATAL_ERROR "Editor artifact target mismatch: expected ${platform}-${arch}, found ${pointer_platform}-${pointer_arch}")
    endif()
    if(platform STREQUAL "linux")
        set(expected_count 3)
    elseif(platform STREQUAL "windows")
        set(expected_count 1)
    elseif(platform STREQUAL "macos")
        set(expected_count 2)
    else()
        message(FATAL_ERROR "Unsupported editor release platform: ${platform}")
    endif()
    if(NOT artifact_count EQUAL expected_count)
        message(FATAL_ERROR "Expected ${expected_count} editor artifacts for ${platform}, found ${artifact_count}")
    endif()
    math(EXPR last_artifact "${artifact_count} - 1")
    set(collected_editor_artifacts "")
    foreach(index RANGE 0 ${last_artifact})
        string(JSON file_name GET "${pointer_json}" artifacts ${index} fileName)
        string(JSON expected_hash GET "${pointer_json}" artifacts ${index} sha256)
        set(artifact "${output_root}/${file_name}")
        require_file("${artifact}")
        file(SHA256 "${artifact}" actual_hash)
        if(NOT actual_hash STREQUAL expected_hash)
            message(FATAL_ERROR "Editor artifact hash mismatch: ${artifact}")
        endif()
        get_filename_component(ext "${file_name}" LAST_EXT)
        if(ext STREQUAL ".exe")
            set(output_name "noveltea-editor-${NOVELTEA_RELEASE_TAG}-${platform}-${arch}-${build_type}.setup.exe")
        elseif(ext STREQUAL ".AppImage" OR ext STREQUAL ".deb" OR ext STREQUAL ".rpm" OR ext STREQUAL ".dmg" OR ext STREQUAL ".zip")
            set(output_name "noveltea-editor-${NOVELTEA_RELEASE_TAG}-${platform}-${arch}-${build_type}${ext}")
        else()
            message(FATAL_ERROR "Unsupported editor artifact in manifest: ${file_name}")
        endif()
        file(REMOVE "${dist}/${output_name}")
        file(COPY_FILE "${artifact}" "${dist}/${output_name}")
        list(APPEND collected_editor_artifacts "${dist}/${output_name}")
    endforeach()
    list(LENGTH collected_editor_artifacts staged_count)
    if(NOT staged_count EQUAL expected_count)
        message(FATAL_ERROR "Expected ${expected_count} collected editor artifacts, found ${staged_count}")
    endif()
elseif(NOVELTEA_PACKAGE_KIND STREQUAL "checksums")
    file(GLOB entries RELATIVE "${dist}" "${dist}/*")
    list(SORT entries)
    set(lines "")
    foreach(entry IN LISTS entries)
        if(entry STREQUAL "SHA256SUMS" OR IS_DIRECTORY "${dist}/${entry}")
            continue()
        endif()
        file(SHA256 "${dist}/${entry}" hash)
        string(APPEND lines "${hash}  ${entry}\n")
    endforeach()
    file(WRITE "${dist}/SHA256SUMS" "${lines}")
else()
    message(FATAL_ERROR "Unsupported package kind: ${NOVELTEA_PACKAGE_KIND}")
endif()
