cmake_minimum_required(VERSION 3.25)
foreach(required NOVELTEA_TEMPLATE_PRESET NOVELTEA_RELEASE_TAG)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} is required")
  endif()
endforeach()

set(root "${CMAKE_CURRENT_LIST_DIR}/..")
cmake_path(ABSOLUTE_PATH root NORMALIZE OUTPUT_VARIABLE root)
set(build "${root}/build/${NOVELTEA_TEMPLATE_PRESET}")
set(cache "${build}/CMakeCache.txt")
if(NOT EXISTS "${cache}")
  message(FATAL_ERROR "Missing configured Web build cache: ${cache}")
endif()
file(STRINGS "${cache}" web_threads_entry REGEX "^NOVELTEA_ENABLE_THREADS:BOOL=(ON|OFF)$")
if(NOT web_threads_entry)
  message(FATAL_ERROR "Configured Web build does not declare NOVELTEA_ENABLE_THREADS: ${cache}")
endif()
if(web_threads_entry MATCHES "=ON$")
  set(threading_suffix "-threads")
  set(threading_feature "web-threads")
  set(minimum_platform "WebAssembly, WebGL 2, IndexedDB, Web Crypto, SharedArrayBuffer, cross-origin isolation")
else()
  set(threading_suffix "")
  set(threading_feature "web-single-threaded")
  set(minimum_platform "WebAssembly, WebGL 2, IndexedDB, Web Crypto")
endif()

set(stage "${root}/build/package/noveltea-player-web-wasm32${threading_suffix}-release")
set(dist "${root}/dist")
set(template_id "web-wasm32${threading_suffix}-release")
set(build_id "${NOVELTEA_RELEASE_TAG}-web-wasm32${threading_suffix}-release")
set(archive_name "noveltea-player-template-${NOVELTEA_RELEASE_TAG}-web-wasm32${threading_suffix}-release.zip")
set(symbol_name "noveltea-player-symbols-${NOVELTEA_RELEASE_TAG}-web-wasm32${threading_suffix}-release.zip")

file(REMOVE_RECURSE "${stage}")
file(MAKE_DIRECTORY "${stage}" "${stage}/assets" "${stage}/licenses" "${dist}")
foreach(required_file player.html player.js player.wasm player.data)
  if(NOT EXISTS "${build}/apps/player/${required_file}")
    message(FATAL_ERROR "Missing Web player output: ${build}/apps/player/${required_file}")
  endif()
endforeach()
foreach(template_file player.js player.wasm player.data)
  file(COPY_FILE "${build}/apps/player/${template_file}" "${stage}/${template_file}")
endforeach()
if(EXISTS "${build}/apps/player/player.wasm.map")
  message(FATAL_ERROR "Release Web template must not include player.wasm.map; publish it only in the symbols artifact")
endif()
if(NOT EXISTS "${build}/apps/player/player.wasm.debug.wasm")
  message(FATAL_ERROR "Release Web player must provide build-matched separate DWARF symbols")
endif()
find_program(NODE_EXECUTABLE node REQUIRED)
execute_process(COMMAND "${NODE_EXECUTABLE}" "${root}/cmake/generate-player-template-metadata.mjs" "${build}/vcpkg_installed" "${stage}" "${NOVELTEA_RELEASE_TAG}" "${build}" COMMAND_ERROR_IS_FATAL ANY)

# Web template payloads are data files, not host executables. Normalize modes
# before descriptor generation and ZIP creation so secure installation sees the
# same permissions declared by template.json on every archive host.
file(GLOB_RECURSE staged_mode_files LIST_DIRECTORIES false "${stage}/*")
foreach(staged_mode_file IN LISTS staged_mode_files)
  file(CHMOD "${staged_mode_file}" PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
endforeach()

file(GLOB_RECURSE staged_files RELATIVE "${stage}" "${stage}/*")
list(SORT staged_files)
set(file_entries "")
set(dependency_entries "")
foreach(relative IN LISTS staged_files)
  if(IS_DIRECTORY "${stage}/${relative}")
    continue()
  endif()
  file(SIZE "${stage}/${relative}" size)
  file(SHA256 "${stage}/${relative}" hash)
  set(kind asset)
  if(relative MATCHES "^licenses/")
    set(kind notice)
  endif()
  if(NOT file_entries STREQUAL "")
    string(APPEND file_entries ",")
  endif()
  string(APPEND file_entries "{\"path\":\"${relative}\",\"size\":${size},\"mode\":420,\"sha256\":\"${hash}\"}")
  if(relative STREQUAL "player.data" OR kind STREQUAL "notice")
    if(NOT dependency_entries STREQUAL "")
      string(APPEND dependency_entries ",")
    endif()
    string(APPEND dependency_entries "{\"path\":\"${relative}\",\"kind\":\"${kind}\"}")
  endif()
endforeach()

file(WRITE "${stage}/template.json" "{\"format\":\"noveltea.player-template\",\"formatVersion\":1,\"templateId\":\"${template_id}\",\"buildId\":\"${build_id}\",\"engineVersion\":\"${NOVELTEA_RELEASE_TAG}\",\"platform\":\"web\",\"architecture\":\"wasm32\",\"minimumPlatformVersion\":\"${minimum_platform}\",\"graphicsBackends\":[\"webgl2\"],\"shaderVariants\":[\"essl-100\"],\"runtimePackageApi\":{\"minimum\":2,\"maximum\":2},\"playerConfigApi\":{\"minimum\":2,\"maximum\":2},\"compiledFeatures\":[\"lua\",\"rmlui\",\"audio\",\"save\",\"${threading_feature}\"],\"capabilities\":[\"network.client\",\"external-url\",\"clipboard.read\",\"clipboard.write\",\"gamepad\"],\"buildFlavor\":\"release\",\"packageAccessModes\":[\"web-fetch\"],\"files\":[${file_entries}],\"runtimeDependencies\":[${dependency_entries}],\"artifacts\":{\"archive\":\"${archive_name}\",\"symbols\":\"${symbol_name}\",\"sbom\":\"SBOM.cdx.json\",\"notices\":\"licenses/THIRD_PARTY_NOTICES.txt\"},\"provenance\":{\"provider\":\"github-attestation\",\"source\":\"${NOVELTEA_RELEASE_TAG}\"},\"host\":{\"assembly\":\"any\",\"requiresToolchain\":false,\"tools\":[]}}\n")

get_filename_component(stage_parent "${stage}" DIRECTORY)
get_filename_component(stage_name "${stage}" NAME)
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${dist}/${archive_name}" --format=zip "${stage_name}" WORKING_DIRECTORY "${stage_parent}" COMMAND_ERROR_IS_FATAL ANY)
set(symbol_stage "${stage_parent}/symbols-${build_id}")
file(REMOVE_RECURSE "${symbol_stage}")
file(MAKE_DIRECTORY "${symbol_stage}")
file(WRITE "${symbol_stage}/BUILD_ID" "${build_id}\n")
file(COPY_FILE "${build}/apps/player/player.wasm.debug.wasm" "${symbol_stage}/player.wasm.debug.wasm")
if(EXISTS "${build}/apps/player/player.wasm.map")
  file(COPY_FILE "${build}/apps/player/player.wasm.map" "${symbol_stage}/player.wasm.map")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${dist}/${symbol_name}" --format=zip "symbols-${build_id}" WORKING_DIRECTORY "${stage_parent}" COMMAND_ERROR_IS_FATAL ANY)
file(COPY_FILE "${stage}/template.json" "${dist}/${template_id}.template.json")
file(COPY_FILE "${stage}/SBOM.cdx.json" "${dist}/${template_id}.SBOM.cdx.json")
file(COPY_FILE "${stage}/licenses/THIRD_PARTY_NOTICES.txt" "${dist}/${template_id}.THIRD_PARTY_NOTICES.txt")
