#include "noveltea/renderer.hpp"

#include "noveltea/assets/assets.hpp"

#include <SDL3/SDL.h>

#include <bgfx/bgfx.h>
#include <bgfx/platform.h>

#include <cstdio>
#include <cstdint>
#include <cstdarg>
#include <cmath>
#include <cstring>
#include <sstream>
#include <vector>

// Embedded compiled shader binaries (generated by shaderc --bin2c).
#include "shaders/vs_triangle_glsl.h"
#include "shaders/fs_triangle_glsl.h"
#include "shaders/vs_triangle_essl.h"
#include "shaders/fs_triangle_essl.h"
#include "shaders/vs_triangle_web.h"
#include "shaders/fs_triangle_web.h"
#include "shaders/vs_quad_glsl.h"
#include "shaders/fs_quad_glsl.h"
#include "shaders/vs_quad_essl.h"
#include "shaders/fs_quad_essl.h"
#include "shaders/vs_quad_web.h"
#include "shaders/fs_quad_web.h"

namespace noveltea {

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

static const bgfx::Memory* shader_mem(const uint8_t* data, uint32_t size)
{
    const bgfx::Memory* mem = bgfx::alloc(size + 1);
    std::memcpy(mem->data, data, size);
    mem->data[size] = 0;
    return mem;
}

static bgfx::ShaderHandle load_shader(bgfx::RendererType::Enum type,
                                      const uint8_t* glsl, uint32_t glsl_len,
                                      const uint8_t* essl, uint32_t essl_len,
                                      const uint8_t* web,  uint32_t web_len)
{
    const uint8_t* data = nullptr;
    uint32_t len = 0;

    switch (type) {
    case bgfx::RendererType::OpenGL:
        data = glsl;
        len = glsl_len;
        break;
    case bgfx::RendererType::OpenGLES:
#if defined(NOVELTEA_PLATFORM_WEB)
        data = web;
        len = web_len;
#else
        data = essl;
        len = essl_len;
#endif
        break;
    default:
        std::fprintf(stderr, "[renderer] unsupported renderer type %d for triangle shader\n",
                     static_cast<int>(type));
        return BGFX_INVALID_HANDLE;
    }

    bgfx::ShaderHandle h = bgfx::createShader(shader_mem(data, len));
    if (!bgfx::isValid(h)) {
        std::fprintf(stderr, "[renderer] failed to create triangle shader\n");
    }
    return h;
}

// ---------------------------------------------------------------------------
// Vertex / index data for a colored triangle
// ---------------------------------------------------------------------------

struct PosColorVertex
{
    float x, y;
    float r, g, b, a;
};

static PosColorVertex s_triangle_vertices[3] = {
    {  0.0f,  0.5f, 1.0f, 0.0f, 0.0f, 1.0f }, // top - red
    { -0.5f, -0.5f, 0.0f, 1.0f, 0.0f, 1.0f }, // bottom-left - green
    {  0.5f, -0.5f, 0.0f, 0.0f, 1.0f, 1.0f }, // bottom-right - blue
};

static const uint16_t s_triangle_indices[3] = { 0, 1, 2 };

enum ViewId : bgfx::ViewId {
    ViewGame2D = 0,
    ViewRuntimeUI = 1,
    ViewTextLab = 2,
    ViewDebugUI = 3,
};

struct QuadVertex
{
    float x, y;
    float u, v;
    float r, g, b, a;
};

static void make_ortho(float* out, float width, float height)
{
    std::memset(out, 0, sizeof(float) * 16);
    out[0] = 2.0f / width;
    out[5] = -2.0f / height;
    out[10] = 1.0f;
    out[12] = -1.0f;
    out[13] = 1.0f;
    out[15] = 1.0f;
}

// ---------------------------------------------------------------------------
// Renderer implementation
// ---------------------------------------------------------------------------

Renderer::Renderer() = default;
Renderer::~Renderer() { shutdown(); }

bool Renderer::initialize(const RendererConfig& config)
{
    if (m_initialized) return true;

    if (!config.native_window) {
        std::fprintf(stderr, "[renderer] no native window provided\n");
        return false;
    }

    bgfx::PlatformData pd{};
    pd.ndt = config.native_display;
    pd.nwh = config.native_window;

    bgfx::Init init;
#if defined(NOVELTEA_PLATFORM_DESKTOP)
    init.type = bgfx::RendererType::OpenGL;
#else
    init.type = bgfx::RendererType::Count; // auto-detect (Android: GLES, Web: GLES/WebGL)
#endif
    init.platformData = pd;
    init.resolution.width = static_cast<uint32_t>(config.width);
    init.resolution.height = static_cast<uint32_t>(config.height);
    init.resolution.reset = config.vsync ? BGFX_RESET_VSYNC : 0;

    if (!bgfx::init(init)) {
        std::fprintf(stderr, "[renderer] bgfx::init failed\n");
        return false;
    }

    m_width = config.width;
    m_height = config.height;
    m_vsync = config.vsync;
    m_initialized = true;

    bgfx::setDebug(BGFX_DEBUG_TEXT);
    bgfx::setViewClear(0, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH, 0x4040c0ff, 1.0f, 0);
    bgfx::setViewRect(ViewGame2D, 0, 0,
        static_cast<uint16_t>(m_width),
        static_cast<uint16_t>(m_height));

    create_triangle();
    create_2d();

    SDL_Log("[renderer] bgfx initialized: %s", renderer_name());
    return true;
}

void Renderer::begin_frame()
{
    bgfx::setViewClear(ViewGame2D, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH, 0x20242cff, 1.0f, 0);
    bgfx::setViewRect(ViewGame2D, 0, 0,
        static_cast<uint16_t>(m_width),
        static_cast<uint16_t>(m_height));
    bgfx::setViewRect(ViewRuntimeUI, 0, 0, static_cast<uint16_t>(m_width), static_cast<uint16_t>(m_height));
    bgfx::setViewRect(ViewTextLab, 0, 0, static_cast<uint16_t>(m_width), static_cast<uint16_t>(m_height));
    bgfx::setViewRect(ViewDebugUI, 0, 0, static_cast<uint16_t>(m_width), static_cast<uint16_t>(m_height));

    float ortho[16];
    make_ortho(ortho, static_cast<float>(m_width), static_cast<float>(m_height));
    bgfx::setViewTransform(ViewGame2D, nullptr, ortho);
    bgfx::setDebug(BGFX_DEBUG_TEXT);
    bgfx::dbgTextClear();
    bgfx::touch(ViewGame2D);

    // Submit triangle geometry for view 0.
    if (bgfx::isValid(bgfx::VertexBufferHandle{m_triangle_vb})
        && bgfx::isValid(bgfx::IndexBufferHandle{m_triangle_ib})
        && bgfx::isValid(bgfx::ProgramHandle{m_triangle_program}))
    {
        bgfx::setVertexBuffer(0, bgfx::VertexBufferHandle{m_triangle_vb});
        bgfx::setIndexBuffer(bgfx::IndexBufferHandle{m_triangle_ib});
        bgfx::submit(ViewGame2D, bgfx::ProgramHandle{m_triangle_program});
    }
}

void Renderer::end_frame()
{
    bgfx::frame();
}

void Renderer::resize(int width, int height)
{
    if (!m_initialized) return;

    m_width = width;
    m_height = height;

    bgfx::reset(
        static_cast<uint32_t>(width),
        static_cast<uint32_t>(height),
        m_vsync ? BGFX_RESET_VSYNC : 0
    );
    bgfx::setViewRect(0, 0, 0,
        static_cast<uint16_t>(width),
        static_cast<uint16_t>(height));
}

void Renderer::draw_demo_2d(float time_seconds)
{
#if defined(NOVELTEA_HAS_RENDER2D)
    if (!m_initialized || !bgfx::isValid(bgfx::ProgramHandle{m_quad_program})) {
        return;
    }

    const float pulse = 0.5f + 0.5f * std::sin(time_seconds * 2.0f);
    QuadBatch batch;
    batch.draw_colored_quad({72.0f, 96.0f, 220.0f, 132.0f}, {0.15f, 0.65f, 0.95f, 0.88f}, 0.1f);
    const uint16_t texture = bgfx::isValid(bgfx::TextureHandle{m_disk_texture})
        ? m_disk_texture
        : m_checker_texture;
    batch.draw_textured_quad(
        {330.0f, 116.0f, 160.0f, 160.0f},
        Texture{texture},
        {0.0f, 0.0f, 1.0f, 1.0f},
        {1.0f, 1.0f, 1.0f, 1.0f},
        0.2f);
    batch.draw_colored_quad({120.0f + pulse * 80.0f, 270.0f, 180.0f, 48.0f}, {0.95f, 0.72f, 0.18f, 0.9f}, 0.3f);
    draw_2d(batch);
#if defined(NOVELTEA_HAS_TEXT_LAB)
    debug_printf(0, 8, 0x0a, "Text lab static text: styled-run target API scaffold");
#endif
#else
    (void)time_seconds;
#endif
}

void Renderer::draw_2d(const QuadBatch& batch)
{
#if defined(NOVELTEA_HAS_RENDER2D)
    if (!m_initialized || !bgfx::isValid(bgfx::ProgramHandle{m_quad_program})) {
        return;
    }

    for (const QuadCommand& command : batch.commands()) {
        submit_quad(command);
    }
#else
    (void)batch;
#endif
}

void Renderer::shutdown()
{
    if (m_initialized) {
        destroy_2d();
        destroy_triangle();
        bgfx::shutdown();
        m_initialized = false;
        std::printf("[renderer] bgfx shutdown\n");
    }
}

void Renderer::create_2d()
{
    const bgfx::RendererType::Enum type = bgfx::getRendererType();
    bgfx::ShaderHandle vs = load_shader(
        type,
        vs_quad_glsl, sizeof(vs_quad_glsl),
        vs_quad_essl, sizeof(vs_quad_essl),
        vs_quad_web, sizeof(vs_quad_web));
    bgfx::ShaderHandle fs = load_shader(
        type,
        fs_quad_glsl, sizeof(fs_quad_glsl),
        fs_quad_essl, sizeof(fs_quad_essl),
        fs_quad_web, sizeof(fs_quad_web));

    if (!bgfx::isValid(vs) || !bgfx::isValid(fs)) {
        if (bgfx::isValid(vs)) bgfx::destroy(vs);
        if (bgfx::isValid(fs)) bgfx::destroy(fs);
        return;
    }

    m_quad_program = bgfx::createProgram(vs, fs, true).idx;
    m_sampler = bgfx::createUniform("s_texColor", bgfx::UniformType::Sampler).idx;
    m_use_texture_uniform = bgfx::createUniform("u_useTexture", bgfx::UniformType::Vec4).idx;

    constexpr uint32_t pixels[16] = {
        0xffffffff, 0xff3b82f6, 0xffffffff, 0xff3b82f6,
        0xff3b82f6, 0xffffffff, 0xff3b82f6, 0xffffffff,
        0xffffffff, 0xff3b82f6, 0xffffffff, 0xff3b82f6,
        0xff3b82f6, 0xffffffff, 0xff3b82f6, 0xffffffff,
    };
    m_checker_texture = bgfx::createTexture2D(
        4, 4, false, 1, bgfx::TextureFormat::RGBA8, BGFX_SAMPLER_U_CLAMP | BGFX_SAMPLER_V_CLAMP,
        bgfx::copy(pixels, sizeof(pixels))).idx;

    m_disk_texture = load_ppm_texture("apps/sandbox/assets/checker.ppm");
    if (bgfx::isValid(bgfx::TextureHandle{m_disk_texture})) {
        m_texture_status = "disk PPM apps/sandbox/assets/checker.ppm";
    } else {
        m_texture_status = "fallback procedural checker";
    }
}

void Renderer::destroy_2d()
{
    if (bgfx::isValid(bgfx::TextureHandle{m_disk_texture})) bgfx::destroy(bgfx::TextureHandle{m_disk_texture});
    if (bgfx::isValid(bgfx::TextureHandle{m_checker_texture})) bgfx::destroy(bgfx::TextureHandle{m_checker_texture});
    if (bgfx::isValid(bgfx::UniformHandle{m_use_texture_uniform})) bgfx::destroy(bgfx::UniformHandle{m_use_texture_uniform});
    if (bgfx::isValid(bgfx::UniformHandle{m_sampler})) bgfx::destroy(bgfx::UniformHandle{m_sampler});
    if (bgfx::isValid(bgfx::ProgramHandle{m_quad_program})) bgfx::destroy(bgfx::ProgramHandle{m_quad_program});
    m_checker_texture = UINT16_MAX;
    m_disk_texture = UINT16_MAX;
    m_use_texture_uniform = UINT16_MAX;
    m_sampler = UINT16_MAX;
    m_quad_program = UINT16_MAX;
}

void Renderer::submit_quad(const QuadCommand& command)
{
    constexpr uint16_t indices[] = {0, 1, 2, 0, 2, 3};
    const float x = command.rect.x;
    const float y = command.rect.y;
    const float w = command.rect.width;
    const float h = command.rect.height;
    const float u0 = command.uv.x;
    const float v0 = command.uv.y;
    const float u1 = command.uv.x + command.uv.width;
    const float v1 = command.uv.y + command.uv.height;
    const Color color = command.color;
    QuadVertex vertices[] = {
        {x, y, u0, v0, color.r, color.g, color.b, color.a},
        {x + w, y, u1, v0, color.r, color.g, color.b, color.a},
        {x + w, y + h, u1, v1, color.r, color.g, color.b, color.a},
        {x, y + h, u0, v1, color.r, color.g, color.b, color.a},
    };
    (void)command.depth;

    bgfx::VertexLayout layout;
    layout.begin()
        .add(bgfx::Attrib::Position, 2, bgfx::AttribType::Float)
        .add(bgfx::Attrib::TexCoord0, 2, bgfx::AttribType::Float)
        .add(bgfx::Attrib::Color0, 4, bgfx::AttribType::Float)
        .end();

    bgfx::TransientVertexBuffer tvb;
    bgfx::TransientIndexBuffer tib;
    if (!bgfx::allocTransientBuffers(&tvb, layout, 4, &tib, 6)) {
        return;
    }
    std::memcpy(tvb.data, vertices, sizeof(vertices));
    std::memcpy(tib.data, indices, sizeof(indices));

    const uint16_t texture = command.texture.handle;
    const bool use_texture = texture != UINT16_MAX && bgfx::isValid(bgfx::TextureHandle{texture});
    const float use_texture_uniform[] = {use_texture ? 1.0f : 0.0f, 0.0f, 0.0f, 0.0f};
    bgfx::setUniform(bgfx::UniformHandle{m_use_texture_uniform}, use_texture_uniform);
    if (use_texture) {
        bgfx::setTexture(0, bgfx::UniformHandle{m_sampler}, bgfx::TextureHandle{texture});
    }
    bgfx::setVertexBuffer(0, &tvb);
    bgfx::setIndexBuffer(&tib);
    bgfx::setState(BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A | BGFX_STATE_BLEND_ALPHA);
    bgfx::submit(ViewGame2D, bgfx::ProgramHandle{m_quad_program});
}

uint16_t Renderer::load_ppm_texture(const std::filesystem::path& path)
{
    const auto bytes = read_binary_file(path);
    if (!bytes) {
        return UINT16_MAX;
    }

    std::string text(bytes->begin(), bytes->end());
    std::istringstream in(text);
    std::string magic;
    int width = 0;
    int height = 0;
    int max_value = 0;
    in >> magic >> width >> height >> max_value;
    if (magic != "P3" || width <= 0 || height <= 0 || max_value <= 0) {
        SDL_Log("[renderer] unsupported texture file %s (expected ASCII PPM P3)", path.string().c_str());
        return UINT16_MAX;
    }

    std::vector<uint32_t> pixels(static_cast<std::size_t>(width * height));
    for (int i = 0; i < width * height; ++i) {
        int r = 0;
        int g = 0;
        int b = 0;
        if (!(in >> r >> g >> b)) {
            SDL_Log("[renderer] incomplete PPM texture %s", path.string().c_str());
            return UINT16_MAX;
        }
        const auto scale = [max_value](int value) -> uint32_t {
            if (value < 0) value = 0;
            if (value > max_value) value = max_value;
            return static_cast<uint32_t>((value * 255) / max_value);
        };
        pixels[static_cast<std::size_t>(i)] = 0xff000000u
            | (scale(b) << 16)
            | (scale(g) << 8)
            | scale(r);
    }

    const bgfx::TextureHandle texture = bgfx::createTexture2D(
        static_cast<uint16_t>(width),
        static_cast<uint16_t>(height),
        false,
        1,
        bgfx::TextureFormat::RGBA8,
        BGFX_SAMPLER_U_CLAMP | BGFX_SAMPLER_V_CLAMP,
        bgfx::copy(pixels.data(), static_cast<uint32_t>(pixels.size() * sizeof(uint32_t))));

    if (!bgfx::isValid(texture)) {
        SDL_Log("[renderer] failed to create texture from %s", path.string().c_str());
        return UINT16_MAX;
    }
    SDL_Log("[renderer] loaded texture: %s (%dx%d)", path.string().c_str(), width, height);
    return texture.idx;
}

const char* Renderer::renderer_name() const
{
    if (!m_initialized) return "uninitialized";
    return bgfx::getRendererName(bgfx::getRendererType());
}

void Renderer::debug_printf(uint16_t x, uint16_t y, uint8_t color, const char* fmt, ...)
{
    if (!m_initialized) return;
    char buf[256];
    va_list args;
    va_start(args, fmt);
    std::vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    bgfx::dbgTextPrintf(x, y, color, "%s", buf);
}

// ---------------------------------------------------------------------------
// Triangle resource lifecycle
// ---------------------------------------------------------------------------

void Renderer::create_triangle()
{
    const bgfx::RendererType::Enum type = bgfx::getRendererType();

    // Load vertex & fragment shaders.
    bgfx::ShaderHandle vs = load_shader(
        type,
        vs_triangle_glsl, sizeof(vs_triangle_glsl),
        vs_triangle_essl, sizeof(vs_triangle_essl),
        vs_triangle_web,  sizeof(vs_triangle_web));
    bgfx::ShaderHandle fs = load_shader(
        type,
        fs_triangle_glsl, sizeof(fs_triangle_glsl),
        fs_triangle_essl, sizeof(fs_triangle_essl),
        fs_triangle_web,  sizeof(fs_triangle_web));

    if (!bgfx::isValid(vs) || !bgfx::isValid(fs)) {
        std::fprintf(stderr, "[renderer] triangle shader load failed; skipping triangle\n");
        if (bgfx::isValid(vs)) bgfx::destroy(vs);
        if (bgfx::isValid(fs)) bgfx::destroy(fs);
        return;
    }

    m_triangle_program = bgfx::createProgram(vs, fs, true /* destroy shaders when program is done */).idx;
    if (!bgfx::isValid(bgfx::ProgramHandle{m_triangle_program})) {
        std::fprintf(stderr, "[renderer] failed to create triangle program\n");
        bgfx::destroy(vs);
        bgfx::destroy(fs);
        return;
    }

    // Vertex layout.
    bgfx::VertexLayout layout;
    layout.begin()
        .add(bgfx::Attrib::Position, 2, bgfx::AttribType::Float)
        .add(bgfx::Attrib::Color0, 4, bgfx::AttribType::Float)
        .end();

    m_triangle_vb = bgfx::createVertexBuffer(
        bgfx::makeRef(s_triangle_vertices, sizeof(s_triangle_vertices)),
        layout
    ).idx;

    m_triangle_ib = bgfx::createIndexBuffer(
        bgfx::makeRef(s_triangle_indices, sizeof(s_triangle_indices))
    ).idx;

    SDL_Log("[renderer] triangle resources created");
}

void Renderer::destroy_triangle()
{
    if (bgfx::isValid(bgfx::ProgramHandle{m_triangle_program})) {
        bgfx::destroy(bgfx::ProgramHandle{m_triangle_program});
    }
    if (bgfx::isValid(bgfx::VertexBufferHandle{m_triangle_vb})) {
        bgfx::destroy(bgfx::VertexBufferHandle{m_triangle_vb});
    }
    if (bgfx::isValid(bgfx::IndexBufferHandle{m_triangle_ib})) {
        bgfx::destroy(bgfx::IndexBufferHandle{m_triangle_ib});
    }

    m_triangle_vb = UINT16_MAX;
    m_triangle_ib = UINT16_MAX;
    m_triangle_program = UINT16_MAX;

    SDL_Log("[renderer] triangle resources destroyed");
}

} // namespace noveltea
