// AUTO-GENERATED by scripts/generate-material-contract-registry.mjs. DO NOT EDIT.

import registry from '../../../../engine/material-contracts/material-contract-registry.json';

export const materialContractRoleIds = [
  'engine-2d',
  'active-text',
  'rmlui-decorator',
  'postprocess',
  'hotspot-overlay',
] as const;

export const materialContractPresetIds = [
  'engine-2d',
  'active-text',
  'rmlui-decorator',
  'postprocess-tint',
  'hotspot-overlay-alpha',
  'hotspot-overlay-custom',
] as const;

export const materialContractFingerprints = {
  'engine-2d': 'sha256:0e4e262891e0e3895803481b735e0747bb62bc49599e4b8de76586139b2e292a',
  'active-text': 'sha256:c62ec9672871d25d0736f7b093016d8835ea372693b9dab9016ea56d145427e2',
  'rmlui-decorator': 'sha256:4d6fa3ddc7c34a2d7ca9fa8102e0881305a1ea684693b47eff6ebebdddaf4a27',
  'postprocess-tint': 'sha256:07983cdd0065e8e8acf3aaf53c6e2c0bb443f8c557561403b0dd4917f4040b10',
  'hotspot-overlay-alpha':
    'sha256:c6676b68043dcc07e21ad86c5552a11e55784bb294a2aecb2ce0bc531fef378e',
  'hotspot-overlay-custom':
    'sha256:14cf3e7f960ec5334f2135358daee569b66949dfecb0b1ae0eac5b57c39e9434',
} as const;

export const materialContractRegistry = {
  ...registry,
  presets: [
    {
      ...registry.presets[0],
      contractFingerprint: materialContractFingerprints['engine-2d'],
    },
    {
      ...registry.presets[1],
      contractFingerprint: materialContractFingerprints['active-text'],
    },
    {
      ...registry.presets[2],
      contractFingerprint: materialContractFingerprints['rmlui-decorator'],
    },
    {
      ...registry.presets[3],
      contractFingerprint: materialContractFingerprints['postprocess-tint'],
    },
    {
      ...registry.presets[4],
      contractFingerprint: materialContractFingerprints['hotspot-overlay-alpha'],
    },
    {
      ...registry.presets[5],
      contractFingerprint: materialContractFingerprints['hotspot-overlay-custom'],
    },
  ],
} as const;

export type MaterialContractRoleId = (typeof materialContractRoleIds)[number];
export type MaterialContractPresetId = (typeof materialContractPresetIds)[number];
