// AUTO-GENERATED by scripts/generate-material-contract-registry.mjs. DO NOT EDIT.

import registry from '../../../../engine/material-contracts/material-contract-registry.json';

export const materialContractRoleIds = [
  'engine-2d',
  'active-text',
  'rmlui-decorator',
  'postprocess',
  'hotspot-overlay',
] as const;

export const materialContractPresetIds = [
  'engine-2d',
  'active-text',
  'rmlui-decorator',
  'postprocess-tint',
  'hotspot-overlay-alpha',
  'hotspot-overlay-custom',
] as const;

export const materialContractFingerprints = {
  'engine-2d': 'sha256:49111ad3e9c928953f510a57100419f761118d42f65bafe1786d56a858ae74b9',
  'active-text': 'sha256:dca98d91d8339c97658f5aa9852bb5213f4601bb5fd4be532c93d7caba606554',
  'rmlui-decorator': 'sha256:13861c8862bc8406cc2a3575a6a81e504c8f85943b9fcb5f9b4de8bf075245f8',
  'postprocess-tint': 'sha256:be4687257959764c5f1eaac0b101615349c727a9671bd515c75dd8d923accdf3',
  'hotspot-overlay-alpha':
    'sha256:7379c072c2c57ad0d5f3bab480bf6487600acdc80d0ea9e4a3b29c900d5adc1f',
  'hotspot-overlay-custom':
    'sha256:252bf9943585748a6647bf4243375ac1c922224be11f52dffa2a7d1ed745eb6d',
} as const;

export const materialContractRegistry = {
  ...registry,
  presets: [
    {
      ...registry.presets[0],
      contractFingerprint: materialContractFingerprints['engine-2d'],
    },
    {
      ...registry.presets[1],
      contractFingerprint: materialContractFingerprints['active-text'],
    },
    {
      ...registry.presets[2],
      contractFingerprint: materialContractFingerprints['rmlui-decorator'],
    },
    {
      ...registry.presets[3],
      contractFingerprint: materialContractFingerprints['postprocess-tint'],
    },
    {
      ...registry.presets[4],
      contractFingerprint: materialContractFingerprints['hotspot-overlay-alpha'],
    },
    {
      ...registry.presets[5],
      contractFingerprint: materialContractFingerprints['hotspot-overlay-custom'],
    },
  ],
} as const;

export type MaterialContractRoleId = (typeof materialContractRoleIds)[number];
export type MaterialContractPresetId = (typeof materialContractPresetIds)[number];
